#ifndef _MODULE_DEF_H
#define _MODULE_DEF_H

typedef enum{
	/*backgroud service*/
	SERVICE_CONTENTPROVIDER,
	SERVICE_MUTIMEDIA,
	SERVICE_SYSLOG,
	SERVICE_WINDOW,
	SERVICE_ENVIRONMENT,
	SERVICE_POWER,
	SERVICE_UPGRADE,

	/*application*/
	ACTIVITY_CLUSTER,
	ACTIVITY_LVDS,

	/*background service manager*/
	SERVICEMGR_CONTENTPROVIDER,
	SERVICEMGR_MUTIMEDIA,
	SERVICEMGR_SYSLOG,
	SERVICEMGR_WINDOW,
	SERVICEMGR_ENVIRONMENT,
	SERVICEMGR_POWER,
	SERVICEMGR_UPGRADE,

	/*application manager*/
	ACTIVITYMGR_CLUSTER,
	ACTIVITYMGR_LVDS,

	/*hardware manager*/
	HARDWAREMGR_BUS,
	HARDWAREMGR_LCD,
	HARDWAREMGR_POWER,
	HARDWAREMGR_STORAGE,
	HARDWAREMGR_CORE,
	HAREWAREMGR_LVDS,
	HAREWAREMGR_USBSTATE,

	/*kanzi applications*/
	KANZIAPP_SPEED,
	KANZIAPP_TACH,
	KANZIAPP_POPUP,
	KANZIAPP_TABICON,
	KANZIAPP_BACKGROUND,
}_MODULE_NAME;

#define MODULE_SUM 30

/*
*
*构造一个用于IPCOBJ_connect第二个参数的字符串
* 参数path必须是一个常量字符串
* example:
*		MAKE_RULES_STR( "/com/saic/IpcUartData" )
*/
#define MAKE_RULES_STR( path ) ("type='signal',path='" path "'")


/*dbus name,dbus interface,dbus path*/
#define _IPC_NAME(name)					("com.saic." name)
#define _IPC_INTERFACE(interface)		(interface ".signal.type")
#define _IPC_PATH(path)					("/com/saic/" path)


/*backgroud service*/
/*SERVICE_CONTENTPROVIDER*/
#define SERVICE_CONTENTPROVIDER_NICK			"ServiceContentProvider"
#define SERVICE_CONTENTPROVIDER_NAME 			_IPC_NAME(SERVICE_CONTENTPROVIDER_NICK)
#define SERVICE_CONTENTPROVIDER_INTERFACE   	_IPC_INTERFACE(SERVICE_CONTENTPROVIDER_NICK)
#define SERVICE_CONTENTPROVIDER_PATH			_IPC_PATH(SERVICE_CONTENTPROVIDER_NICK)

/*SERVICE_MUTIMEDIA*/
#define	SERVICE_MUTIMEDIA_NICK					"ServiceMutiMedia"
#define	SERVICE_MUTIMEDIA_NAME					_IPC_NAME(SERVICE_MUTIMEDIA_NICK)
#define	SERVICE_MUTIMEDIA_INTERFACE				_IPC_INTERFACE(SERVICE_MUTIMEDIA_NICK)
#define	SERVICE_MUTIMEDIA_PATH					_IPC_PATH(SERVICE_MUTIMEDIA_NICK)

/*SERVICE_SYSLOG*/                          	
#define	SERVICE_SYSLOG_NICK						"ServiceSysLog"
#define	SERVICE_SYSLOG_NAME						_IPC_NAME(SERVICE_SYSLOG_NICK)
#define	SERVICE_SYSLOG_INTERFACE				_IPC_INTERFACE(SERVICE_SYSLOG_NICK)
#define	SERVICE_SYSLOG_PATH						_IPC_PATH(SERVICE_SYSLOG_NICK)

/*SERVICE_WINDOW*/                          	
#define	SERVICE_WINDOW_NICK						"ServiceWindow"
#define	SERVICE_WINDOW_NAME						_IPC_NAME(SERVICE_WINDOW_NICK)
#define	SERVICE_WINDOW_INTERFACE				_IPC_INTERFACE(SERVICE_WINDOW_NICK)
#define	SERVICE_WINDOW_PATH						_IPC_PATH(SERVICE_WINDOW_NICK)

/*SERVICE_ENVIRONMENT*/                     	
#define	SERVICE_ENVIRONMENT_NICK				"ServiceEnvironment"
#define	SERVICE_ENVIRONMENT_NAME				_IPC_NAME(SERVICE_ENVIRONMENT_NICK)
#define	SERVICE_ENVIRONMENT_INTERFACE			_IPC_INTERFACE(SERVICE_ENVIRONMENT_NICK)
#define	SERVICE_ENVIRONMENT_PATH				_IPC_PATH(SERVICE_ENVIRONMENT_NICK)

/*SERVICE_POWER*/                           	
#define	SERVICE_POWER_NICK						"ServicePower"
#define	SERVICE_POWER_NAME						_IPC_NAME(SERVICE_POWER_NICK)
#define	SERVICE_POWER_INTERFACE					_IPC_INTERFACE(SERVICE_POWER_NICK)
#define	SERVICE_POWER_PATH						_IPC_PATH(SERVICE_POWER_NICK)

/*SERVICE_UPGRADE*/                         	
#define	SERVICE_UPGRADE_NICK					"ServiceUpgrade"
#define	SERVICE_UPGRADE_NAME					_IPC_NAME(SERVICE_UPGRADE_NICK)
#define	SERVICE_UPGRADE_INTERFACE				_IPC_INTERFACE(SERVICE_UPGRADE_NICK)
#define	SERVICE_UPGRADE_PATH					_IPC_PATH(SERVICE_UPGRADE_NICK)

/*background service manager*/
/*SERVICEMGR_CONTENTPROVIDER*/
#define	SERVICEMGR_CONTENTPROVIDER_NICK			"ServiceMgrContentprovider"
#define	SERVICEMGR_CONTENTPROVIDER_NAME			_IPC_NAME(SERVICEMGR_CONTENTPROVIDER_NICK)
#define	SERVICEMGR_CONTENTPROVIDER_INTERFACE	_IPC_INTERFACE(SERVICEMGR_CONTENTPROVIDER_NICK)
#define	SERVICEMGR_CONTENTPROVIDER_PATH			_IPC_PATH(SERVICEMGR_CONTENTPROVIDER_NICK)

/*SERVICEMGR_MUTIMEDIA*/
#define SERVICEMGR_MUTIMEDIA_NICK				"ServiceMgrMutiMedia"
#define SERVICEMGR_MUTIMEDIA_NAME				_IPC_NAME(SERVICEMGR_MUTIMEDIA_NICK)
#define SERVICEMGR_MUTIMEDIA_INTERFACE			_IPC_INTERFACE(SERVICEMGR_MUTIMEDIA_NICK)
#define SERVICEMGR_MUTIMEDIA_PATH				_IPC_PATH(SERVICEMGR_MUTIMEDIA_NICK)

/*SERVICEMGR_SYSLOG*/
#define SERVICEMGR_SYSLOG_NICK					"ServiceMgrSysLog"
#define SERVICEMGR_SYSLOG_NAME					_IPC_NAME(SERVICEMGR_SYSLOG_NICK)
#define SERVICEMGR_SYSLOG_INTERFACE				_IPC_INTERFACE(SERVICEMGR_SYSLOG_NICK)
#define SERVICEMGR_SYSLOG_PATH					_IPC_PATH(SERVICEMGR_SYSLOG_NICK)

/*SERVICEMGR_WINDOW*/
#define SERVICEMGR_WINDOW_NICK					"ServiceMgrWindow"
#define SERVICEMGR_WINDOW_NAME					_IPC_NAME(SERVICEMGR_WINDOW_NICK)
#define SERVICEMGR_WINDOW_INTERFACE				_IPC_INTERFACE(SERVICEMGR_WINDOW_NICK)
#define SERVICEMGR_WINDOW_PATH					_IPC_PATH(SERVICEMGR_WINDOW_NICK)

/*SERVICEMGR_ENVIRONMENT*/
#define SERVICEMGR_ENVIRONMENT_NICK				"ServiceMgrEnvironment"
#define SERVICEMGR_ENVIRONMENT_NAME				_IPC_NAME(SERVICEMGR_ENVIRONMENT_NICK)
#define SERVICEMGR_ENVIRONMENT_INTERFACE		_IPC_INTERFACE(SERVICEMGR_ENVIRONMENT_NICK)
#define SERVICEMGR_ENVIRONMENT_PATH				_IPC_PATH(SERVICEMGR_ENVIRONMENT_NICK)

/*SERVICEMGR_POWER*/
#define SERVICEMGR_POWER_NICK					"ServiceMgrPower"
#define SERVICEMGR_POWER_NAME					_IPC_NAME(SERVICEMGR_POWER_NICK)
#define SERVICEMGR_POWER_INTERFACE				_IPC_INTERFACE(SERVICEMGR_POWER_NICK)
#define SERVICEMGR_POWER_PATH					_IPC_PATH(SERVICEMGR_POWER_NICK)

/*SERVICEMGR_UPGRADE*/
#define SERVICEMGR_UPGRADE_NICK					"ServiceMgrUpgrade"
#define SERVICEMGR_UPGRADE_NAME					_IPC_NAME(SERVICEMGR_UPGRADE_NICK)
#define SERVICEMGR_UPGRADE_INTERFACE			_IPC_INTERFACE(SERVICEMGR_UPGRADE_NICK)
#define SERVICEMGR_UPGRADE_PATH					_IPC_PATH(SERVICEMGR_UPGRADE_NICK)

/*hardware manager*/
/*HARDWAREMGR_BUS*/
#define HARDWAREMGR_BUS_NICK					"HardwareMgrBus"
#define HARDWAREMGR_BUS_NAME					_IPC_NAME(HARDWAREMGR_BUS_NICK)
#define HARDWAREMGR_BUS_INTERFACE				_IPC_INTERFACE(HARDWAREMGR_BUS_NICK)
#define HARDWAREMGR_BUS_PATH					_IPC_PATH(HARDWAREMGR_BUS_NICK)

/*HARDWAREMGR_LCD*/
#define HARDWAREMGR_LCD_NICK					"HardwareMgrLcd"
#define HARDWAREMGR_LCD_NAME					_IPC_NAME(HARDWAREMGR_LCD_NICK)
#define HARDWAREMGR_LCD_INTERFACE				_IPC_INTERFACE(HARDWAREMGR_LCD_NICK)
#define HARDWAREMGR_LCD_PATH					_IPC_PATH(HARDWAREMGR_LCD_NICK)

/*HARDWAREMGR_POWER*/
#define HARDWAREMGR_POWER_NICK					"HardwareMgrPower"
#define HARDWAREMGR_POWER_NAME					_IPC_NAME(HARDWAREMGR_POWER_NICK)
#define HARDWAREMGR_POWER_INTERFACE				_IPC_INTERFACE(HARDWAREMGR_POWER_NICK)
#define HARDWAREMGR_POWER_PATH					_IPC_PATH(HARDWAREMGR_POWER_NICK)

/*HARDWAREMGR_STORAGE*/
#define HARDWAREMGR_STORAGE_NICK				"HardwareMgrStorage"
#define HARDWAREMGR_STORAGE_NAME				_IPC_NAME(HARDWAREMGR_STORAGE_NICK)
#define HARDWAREMGR_STORAGE_INTERFACE			_IPC_INTERFACE(HARDWAREMGR_STORAGE_NICK)
#define HARDWAREMGR_STORAGE_PATH				_IPC_PATH(HARDWAREMGR_STORAGE_NICK)

/*HARDWAREMGR_CORE*/
#define HARDWAREMGR_CORE_NICK					"HardwareMgrCore"
#define HARDWAREMGR_CORE_NAME					_IPC_NAME(HARDWAREMGR_CORE_NICK)
#define HARDWAREMGR_CORE_INTERFACE				_IPC_INTERFACE(HARDWAREMGR_CORE_NICK)
#define HARDWAREMGR_CORE_PATH					_IPC_PATH(HARDWAREMGR_CORE_NICK)

/*HAREWAREMGR_LVDS*/
#define HAREWAREMGR_LVDS_NICK					"HardwareMgrLvds"
#define HAREWAREMGR_LVDS_NAME					_IPC_NAME(HAREWAREMGR_LVDS_NICK)
#define HAREWAREMGR_LVDS_INTERFACE				_IPC_INTERFACE(HAREWAREMGR_LVDS_NICK)
#define HAREWAREMGR_LVDS_PATH					_IPC_PATH(HAREWAREMGR_LVDS_NICK)

/*HAREWAREMGR_USBSTATE*/
#define HAREWAREMGR_USBSTATE_NICK				"HardwareMgrUsbState"
#define HAREWAREMGR_USBSTATE_NAME				_IPC_NAME(HAREWAREMGR_USBSTATE_NICK)
#define HAREWAREMGR_USBSTATE_INTERFACE			_IPC_INTERFACE(HAREWAREMGR_USBSTATE_NICK)
#define HAREWAREMGR_USBSTATE_PATH				_IPC_PATH(HAREWAREMGR_USBSTATE_NICK)

/*application*/
/*ACTIVITY_CLUSTER*/
#define ACTIVITY_CLUSTER_NICK					"ActivityCluster"
#define ACTIVITY_CLUSTER_NAME					_IPC_NAME(ACTIVITY_CLUSTER_NICK)
#define ACTIVITY_CLUSTER_INTERFACE				_IPC_INTERFACE(ACTIVITY_CLUSTER_NICK)
#define ACTIVITY_CLUSTER_PATH					_IPC_PATH(ACTIVITY_CLUSTER_NICK)

/*ACTIVITY_LVDS*/
#define ACTIVITY_LVDS_NICK						"ActivityLvds"
#define ACTIVITY_LVDS_NAME						_IPC_NAME(ACTIVITY_LVDS_NICK)
#define ACTIVITY_LVDS_INTERFACE					_IPC_INTERFACE(ACTIVITY_LVDS_NICK)
#define ACTIVITY_LVDS_PATH						_IPC_PATH(ACTIVITY_LVDS_NICK)

/*application manager*/
/*ACTIVITYMGR_CLUSTER*/
#define ACTIVITYMGR_CLUSTER_NICK				"ActivityMgrCluster"
#define ACTIVITYMGR_CLUSTER_NAME				_IPC_NAME(ACTIVITYMGR_CLUSTER_NICK)
#define ACTIVITYMGR_CLUSTER_INTERFACE			_IPC_INTERFACE(ACTIVITYMGR_CLUSTER_NICK)
#define ACTIVITYMGR_CLUSTER_PATH				_IPC_PATH(ACTIVITYMGR_CLUSTER_NICK)

/*ACTIVITYMGR_LVDS*/
#define ACTIVITYMGR_LVDS_NICK					"ActivityMgrLvds"
#define ACTIVITYMGR_LVDS_NAME					_IPC_NAME(ACTIVITYMGR_LVDS_NICK)
#define ACTIVITYMGR_LVDS_INTERFACE				_IPC_INTERFACE(ACTIVITYMGR_LVDS_NICK)
#define ACTIVITYMGR_LVDS_PATH					_IPC_PATH(ACTIVITYMGR_LVDS_NICK)

/*kanzi applications*/
/*KANZIAPP_SPEED*/
#define KANZIAPP_SPEED_NICK					"KanziAppSpeed"
#define KANZIAPP_SPEED_NAME					_IPC_NAME(KANZIAPP_SPEED_NICK)
#define KANZIAPP_SPEED_INTERFACE				_IPC_INTERFACE(KANZIAPP_SPEED_NICK)
#define KANZIAPP_SPEED_PATH					_IPC_PATH(KANZIAPP_SPEED_NICK)

/*KANZIAPP_TACH*/
#define KANZIAPP_TACH_NICK					"KanziAppTach"
#define KANZIAPP_TACH_NAME					_IPC_NAME(KANZIAPP_TACH_NICK)
#define KANZIAPP_TACH_INTERFACE				_IPC_INTERFACE(KANZIAPP_TACH_NICK)
#define KANZIAPP_TACH_PATH					_IPC_PATH(KANZIAPP_TACH_NICK)

/*KANZIAPP_POPUP*/
#define KANZIAPP_POPUP_NICK					"KanziAppPopup"
#define KANZIAPP_POPUP_NAME					_IPC_NAME(KANZIAPP_POPUP_NICK)
#define KANZIAPP_POPUP_INTERFACE				_IPC_INTERFACE(KANZIAPP_POPUP_NICK)
#define KANZIAPP_POPUP_PATH					_IPC_PATH(KANZIAPP_POPUP_NICK)

/*KANZIAPP_TABICON*/
#define KANZIAPP_TABICON_NICK					"KanziAppTabicon"
#define KANZIAPP_TABICON_NAME					_IPC_NAME(KANZIAPP_TABICON_NICK)
#define KANZIAPP_TABICON_INTERFACE				_IPC_INTERFACE(KANZIAPP_TABICON_NICK)
#define KANZIAPP_TABICON_PATH					_IPC_PATH(KANZIAPP_TABICON_NICK)

/*KANZIAPP_BACKGROUND*/
#define KANZIAPP_BACKGROUND_NICK					"KanziAppBackground"
#define KANZIAPP_BACKGROUND_NAME					_IPC_NAME(KANZIAPP_BACKGROUND_NICK)
#define KANZIAPP_BACKGROUND_INTERFACE				_IPC_INTERFACE(KANZIAPP_BACKGROUND_NICK)
#define KANZIAPP_BACKGROUND_PATH					_IPC_PATH(KANZIAPP_BACKGROUND_NICK)

#endif
