#include "popup_priority.h"
#include "Message_Def.h"


/*power on*/
#define POPUP_PRIORITY_ON_A(id) [id &0xffff] = POPUP_POWER_ON | POPUP_PRIORITY_LEVEL_A
#define POPUP_PRIORITY_ON_B(id) [id &0xffff] = POPUP_POWER_ON | POPUP_PRIORITY_LEVEL_B
#define POPUP_PRIORITY_ON_C(id) [id &0xffff] = POPUP_POWER_ON | POPUP_PRIORITY_LEVEL_C

/*power off*/
#define POPUP_PRIORITY_OFF_A(id) [id &0xffff] = POPUP_PRIORITY_LEVEL_A
#define POPUP_PRIORITY_OFF_B(id) [id &0xffff] = POPUP_PRIORITY_LEVEL_B
#define POPUP_PRIORITY_OFF_C(id) [id &0xffff] = POPUP_PRIORITY_LEVEL_C



/*
*
*
*
*
*/


int get_messageid_priority(unsigned int messageid)
{
/*priority byte array*/
	static unsigned char popup_priority_table[SERVICE_DI_MESSAGE_MAX&0xffff] = {
		//A class
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_LF	),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_RF	),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_LB	),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_RB	),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_EC	),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_T	),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_LF_OPEN_RUN),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_RF_OPEN_RUN),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_LB_OPEN_RUN),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_RB_OPEN_RUN),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_EC_OPEN_RUN),
		POPUP_PRIORITY_ON_A( SERVICE_DI_DOOR_T_OPEN_RUN),
		POPUP_PRIORITY_ON_A( SERVICE_DI_ACC_TAKE_OVER_MESSAGE),
		POPUP_PRIORITY_ON_A( SERVICE_DI_FCW_WARNING_ECHO_MESSAGE),
	    //B class
		POPUP_PRIORITY_ON_B( SERVICE_DI_USE_KEY_TO_START_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_SELECT_NEUTRAL_TO_RESTART_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_LOW_WASHER_FLUID_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_LONG_PRESS_BUTTON_ENGINE_OFF_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_PRESS_BUTTON_ENGINE_OFF_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_PRESS_BRAKE_SHIFT_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_ENGAGE_PARK_OR_NEUTRAL_TO_START_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_PRESS_CLUTCH_MESSAGE),
		POPUP_PRIORITY_ON_B( SERVICE_DI_DOUBLE_PRESS_BUTTON_ENGINE_OFF_MESSAGE),
	    //C class
		POPUP_PRIORITY_ON_C( SERVICE_DI_EPB_ASSIST1_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_EPB_ASSIST2_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_EPB_ASSIST3_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_EPB_ASSIST4_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_EPB_ASSIST5_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ENGINE_COOLANT_TEMP_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_START_STOP_BUTTON_FAILED_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_CLUTCH_SWITCH_FAULT_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_KEY_BATTERY_LOW_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LOCK_STATUS_ON_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LOCK_STATUS_OFF_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LOCK_STATUS_FAIL_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_HHC_FAIL_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AUTOHOLD_FAULT_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AUTOHOLD_ASSIST1_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AUTOHOLD_ASSIST2_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AUTOHOLD_ASSIST3_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AUTOHOLD_ASSIST4_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AUTOHOLD_ASSIST5_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ALTERNATOR_CHARGE_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_SEAT_BELT_DRIVER_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_FASTEN_SEATBELT_TO_RESTART_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LOW_FUEL_ECHO_MESSAGE_LOW),
		POPUP_PRIORITY_ON_C( SERVICE_DI_IGNITION_RELAY_FAILED_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_OVERSPEED_WARNING_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_POWER_LIFTGATE_SYSTEM_FAULT_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_POWER_LIFTGATE_SYSTEM_LIMIT_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_POWER_LIFTGATE_MANUAL_CLOSE_REQUEST_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_SIA_REMINDER_SUGGEST_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_FICM_SIA_REMINDER_SUGGEST_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_DOOR_LF_OPEN_STOP),
		POPUP_PRIORITY_ON_C( SERVICE_DI_DOOR_RF_OPEN_STOP),
		POPUP_PRIORITY_ON_C( SERVICE_DI_DOOR_LB_OPEN_STOP),
		POPUP_PRIORITY_ON_C( SERVICE_DI_DOOR_RB_OPEN_STOP),
		POPUP_PRIORITY_ON_C( SERVICE_DI_DOOR_EC_OPEN_STOP),
		POPUP_PRIORITY_ON_C( SERVICE_DI_DOOR_T_OPEN_STOP),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ATS_MODE_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ALL_WHEEL_DRIVE_INSERVICE_DICATION_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LEFT_REGULATE_STEERING_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LEFT_REGULATE_STREERING_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_RIGHT_REGULATE_STEERING_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LOW_FUEL_ECHO_MESSAGE_CRITICAL),
		POPUP_PRIORITY_ON_C( SERVICE_DI_FRONT_FOG_ON_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_REAR_FOG_ON_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_MAIN_BEAM_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ENGINE_DISABLED_MESSAGE),
		/* ADAS功能 begin*/
		POPUP_PRIORITY_ON_C( SERVICE_DI_ACC_SYSTEM_STAND_BY_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ACC_SENSOR_BLOCK_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ACC_SYSTEM_CANCEL_REQUEST_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ACC_SYSTEM_UNAVAILABLE_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ACC_SYSTEM_OFF_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_ACC_SYSTEM_ON_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_FVCM_FAULT_MESSASGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AEB_SYSTEM_UNAVAILABE_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AEB_SYSTEM_OFF_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AEB_SYSTEM_ON_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_AEB_ACTIVE_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LDW_SYSTEM_OFF_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LDW_STAND_BY_ECHO_MESSAGE),
	//	POPUP_PRIORITY_ON_C( SERVICE_DI_DOOR_LFCE_DI_LDW_SYSTEM_CROSSING_LANE_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_LDW_UNAVAILABLE_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_FCW_SYSTEM_OFF_ECHO_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_FCW_SYSTEM_ON_ECHO_MESSAGE),	
		POPUP_PRIORITY_ON_C( SERVICE_DI_FCW_SYSTEM_UNAVAILABLE_ECHO_MESSAGE),	
		POPUP_PRIORITY_ON_C( SERVICE_DI_SAS_SYSTEM_FAULT_MESSAGE),
		POPUP_PRIORITY_ON_C( SERVICE_DI_SAS_SYSTEM_SPEED_LIMIT_REMINDER_MESSAGE),	
		///off A
		POPUP_PRIORITY_OFF_A( SERVICE_DI_DOOR_RF_OPEN_POWEROFF),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_DOOR_LF_OPEN_POWEROFF),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_DOOR_LB_OPEN_POWEROFF),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_DOOR_RB_OPEN_POWEROFF),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_DOOR_EC_OPEN_POWEROFF),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_DOOR_T_OPEN_POWEROFF),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_PUT_SHIFTER_TO_PARK_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_IGNITION_KEY_ON_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_LIGHTS_ON_KEY_OUT_WARNING_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_PRESS_BRAKE_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_NO_SMART_KEY_DETECTED_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_NO_KEY_DETECTED_PRESS_CLUTCH_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_PUT_KEY_INTO_BACKUP_POSITION_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_PEPS_ANTENNA_FAULT_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_ESCL_FAULT_LEVEL2_ECHO_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_NO_KEY_DETECTED_PRESS_BRAKE_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_TAKE_SMART_KEY_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_KEY_OFF_WHEEL_NOT_STRAIGHT_REMINDER_MESSAGE),
		POPUP_PRIORITY_OFF_A( SERVICE_DI_ALARM_TRIGGERED_MESSAGE),
	};
	
	return (int)(popup_priority_table[ messageid & 0xffff ]);
}


