#include "Message_Def.h"
#include "Table_Def.h"
#include "Module_Def.h"


static const char* target_app[] = {
   MODULE_APP_CLUSTER_PATH
};

static const char* target_aud[] = {
	MODULE_SERVICE_AUDIO_MGR_PATH
};

static const char* target_app_aud[] = {
    MODULE_APP_CLUSTER_PATH,
    MODULE_SERVICE_AUDIO_MGR_PATH
};

static const char* target_app_sys[] = {
    MODULE_APP_CLUSTER_PATH,
    MODULE_SERVICE_SYSTEM_PATH
};

static const char* target_app_pwr[] = {
    MODULE_APP_CLUSTER_PATH,
    MODULE_SERVICE_POWER_PATH
};

static const char* target_tabicon[] = {
	KANZIAPP_TABICON_PATH
};

static const char* target_background[] = {
	KANZIAPP_BACKGROUND_PATH
};


struct FlashAttr CruiseFlash[] = {
	FLASH_OFF(),
	FLASH_DIR(),
	FLASH_DIR(),
    FLASH_ON( -1 , 2 , 1000 , 0 , 1000 ),
    
    FLASH_RESET()
};

struct FlashAttr CoolantFlash[] = {
	FLASH_OFF(),
	FLASH_DIR(),
    FLASH_ON( -1 , 1 , 1000 , 2 , 1000 ),
	FLASH_DIR(),
	
	FLASH_RESET()
};

struct FlashAttr MilFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON(-1, 1,500 , 0 , 500 ),
    FLASH_ON(-1, 1,250 , 0 , 250 ),
    FLASH_ON(-1, 1,1000 ,0 , 1000 ),
    
    FLASH_RESET()
};

struct FlashAttr StopStartFlash[] = {
	FLASH_OFF(),
	FLASH_DIR(),
    FLASH_ON(3,1,250 , 0 , 250 ),
    
    FLASH_RESET()
};

struct FlashAttr EpsSasFaultFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON( -1 , 0 , 1000 , 1 , 1000 ),
    FLASH_DIR(),
    
    FLASH_RESET()
};


struct FlashAttr TpmsFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON( -1 , 0 , 1000 , 1, 1000 ),
    
    FLASH_RESET()
};

struct FlashAttr HdcFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON( -1 , 0 , 250 , 1 , 250 ),
    FLASH_DIR(),
    FLASH_ON( -1 , 0 , 250 , 3 , 250 ),
    
    FLASH_RESET()
};

struct FlashAttr ScsFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON( -1 , 0 , 250 , 1 , 250 ),
    
    FLASH_RESET()  
};

struct FlashAttr SeatBeltFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 0 , 1000 , 2 , 1000 ),
    FLASH_DIR(),
    
    FLASH_RESET()
};

struct FlashAttr SrsFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON( -1 , 0 , 1000 , 1 , 1000 ),
    
    FLASH_RESET()
};


struct FlashAttr VehicleWithKeyLampFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON(-1, 2, 1000 , 1 , 1000),
    FLASH_ON(-1, 2, 425 , 1, 75 ),
    FLASH_ON(-1, 2, 2925 , 1 , 75),
    
    FLASH_RESET()
};

//
struct FlashAttr TccmFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_DIR(),
    FLASH_ON(-1 , 0 , 1000 , 2 ,1000 ),
    
    FLASH_RESET()
};

struct FlashAttr EpbStatusFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON( -1 , 0 , 250 , 1, 250 ) ,
    FLASH_DIR() ,
    
    FLASH_RESET()
};

struct FlashAttr EpbFaultFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON(-1 , 0 , 250 , 1 , 250 )  ,
    
    FLASH_RESET()  
};

struct FlashAttr LowFuelFlash[] = {
    FLASH_OFF(),
    FLASH_DIR(),
    FLASH_ON( -1 , 1 , 1000 , 2 , 1000 ),
    
    FLASH_RESET()
};

struct FlashAttr OverSpeedWarningFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 1 , 1000 , 0 , 1000 ),
    
    FLASH_RESET()
};



//1.定速巡航
//	SERVICE_DI_CRUISE_LAMP
//	SERVICE_DI_CRUISE_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_CRUISE_LAMP) = {
	DATA_ENTRY_FLASH( 0,0,3,0,3, CruiseFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_CRUISE_ECHO_MESSAGE) = {
		DATA_ENTRY( 0,3,3,0,3),
		DATA_ENTRY( 0,6,1,0,1),
};

//2.发动机冷却液报警
//	SERVICE_DI_ENGINE_COOLANT_TEMP_LAMP
//	SERVICE_DI_ENGINE_COOLANT_TEMP_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_ENGINE_COOLANT_TEMP_LAMP) = {
	DATA_ENTRY_FLASH( 1 , 0 , 3 , 0 , 3 ,CoolantFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_ENGINE_COOLANT_TEMP_ECHO_MESSAGE) = {
	DATA_ENTRY( 1 , 3, 3 , 0 , 1 ),
	DATA_ENTRY( 1 , 6, 1 , 0 , 1 ),
};

//3.电传线控报警

//	SERVICE_DI_DRIVE_BY_WIRE_LAMP
//	SERVICE_DI_DRIVE_BY_WIRE_LAMP_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_DRIVE_BY_WIRE_LAMP) = {
	DATA_ENTRY( 2 , 0 , 1 , 0 , 1),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DRIVE_BY_WIRE_LAMP_ECHO_MESSAGE) = {
	DATA_ENTRY( 2 , 1, 1 , 0 , 1 ),
	DATA_ENTRY( 2 , 2, 1 , 0 , 1 ),
};

//4.故障指示灯报警
//	SERVICE_DI_MIL_LAMP
//	SERVICE_DI_MIL_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_MIL_LAMP) = {
	DATA_ENTRY_FLASH( 3 , 0 , 4 , 0 , 4 ,MilFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_MIL_ECHO_MESSAGE) = {
	DATA_ENTRY( 3 , 4 , 1 , 0 , 1),
	DATA_ENTRY( 3 , 5 , 1 , 0 , 1),
};

//5.交流发电机充电故障报警

//SERVICE_DI_ALTERNATOR_CHARGE_LAMP
//SERVICE_DI_ALTERNATOR_CHARGE_ECHO_MESSAGE
//SERVICE_DI_SHED_LEVEL_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_ALTERNATOR_CHARGE_LAMP) = {
	DATA_ENTRY( 4 , 0 , 1 , 0 , 1),
};
__DECLARE_DATA_TABLE(SERVICE_DI_ALTERNATOR_CHARGE_ECHO_MESSAGE) = {
	DATA_ENTRY( 4 , 1 , 1 , 0 , 1),
	DATA_ENTRY( 4 , 2 , 1 , 0 , 1),

};
__DECLARE_DATA_TABLE(SERVICE_DI_SHED_LEVEL_ECHO_MESSAGE) = {
	DATA_ENTRY( 4 , 3, 2, 0 , 2 ),
	DATA_ENTRY( 4 , 5, 1, 0 , 1 ),
};

//6.机油压力低
//SERVICE_DI_OIL_PRESSURE_LAMP
//SERVICE_DI_OIL_PRESSURE_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_OIL_PRESSURE_LAMP) = {
	DATA_ENTRY( 5 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_OIL_PRESSURE_ECHO_MESSAGE) = {
	DATA_ENTRY( 5 , 1 , 1 , 0 , 1 ),
	DATA_ENTRY( 5 , 2 , 1 , 0 , 1 ),
};

//7.启停动作或抑制指示

//SERVICE_DI_STOP_START_ACTIVE_LAMP
//SERVICE_DI_STOP_START_ACTIVE_ECHO_MESSAGE
//SERVICE_DI_STOP_START_FAULT_LAMP
//SERVICE_DI_STOP_START_FAULT_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_STOP_START_ACTIVE_LAMP) = {
	DATA_ENTRY_FLASH( 6 , 0 , 2 , 0 , 2 ,StopStartFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_STOP_START_ACTIVE_ECHO_MESSAGE) = {
	DATA_ENTRY( 6 , 2 , 2 , 0 , 2 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_STOP_START_FAULT_LAMP) = {
	DATA_ENTRY( 6 , 4 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_STOP_START_FAULT_MESSAGE) = {
	DATA_ENTRY( 6 , 5 , 1 , 0 , 1 ),
	DATA_ENTRY( 6 , 6 , 1 , 0 , 1 ),
};


//8.EPS，SAS，ESCL，fault warning1

//SERVICE_DI_STEERING_WHEEL_LAMP
//SERVICE_DI_EPS_FAULT_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_STEERING_WHEEL_LAMP) = {
	DATA_ENTRY_FLASH( 7 , 0 , 2 , 0 , 3 ,EpsSasFaultFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_EPS_FAULT_ECHO_MESSAGE) = {
		DATA_ENTRY( 7 , 2 , 2 , 0 , 2 ),
		DATA_ENTRY( 7 , 4 , 1 , 0 , 1 ),
};


//9.EPS，SAS，ESCL，fault warning2

//SERVICE_DI_SAS_FAULT_ECHO_MESSAGE
//SERVICE_DI_SAS_UNCALIBRATION_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_FAULT_ECHO_MESSAGE) = {
	DATA_ENTRY( 8 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 8 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_UNCALIBRATION_ECHO_MESSAGE) = {
	DATA_ENTRY( 8 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 8 , 3 , 1 , 0 , 1 ),
};


//10.TPMS故障1

//SERVICE_DI_TPMS_LAMP
//SERVICE_DI_TPMS_WARN_ECHO_MESSAGE
//SERVICE_DI_TPMS_SYSTEM_FAIL_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_TPMS_LAMP) = {
	DATA_ENTRY_FLASH( 9 , 0 , 2 , 0 , 2 ,TpmsFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_TPMS_WARN_ECHO_MESSAGE) = {
	DATA_ENTRY( 9 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 9 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_TPMS_SYSTEM_FAIL_ECHO_MESSAGE) = {
		DATA_ENTRY( 9 , 4 , 1 , 0 , 1 ),
		DATA_ENTRY( 9 , 5 , 1 , 0 , 1 ),
};

//14.ABS故障报警

//SERVICE_DI_ABS_LAMP
//SERVICE_DI_ABS_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_ABS_LAMP) = {
	DATA_ENTRY( 10 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_ABS_ECHO_MESSAGE) = {
		DATA_ENTRY( 10 , 1 , 1 , 0 , 1 ),
		DATA_ENTRY( 10 , 2 , 1 , 0 , 1 ),
};
//15.HDC启动指示故障报警

//SERVICE_DI_HDC_LAMP
//SERVICE_DI_HDC_FAULT_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_HDC_LAMP) = {
	DATA_ENTRY_FLASH( 11 , 0 , 4 , 0 , 4 , HdcFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_HDC_FAULT_MESSAGE) = {
	DATA_ENTRY( 11 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 11 , 5 , 1 , 0 , 1 ),
};

//16.SCS启动，故障报警
//SERVICE_DI_DSC_LAMP
//SERVICE_DI_DSC_FAULT_MESSAGE
//SERVICE_DI_TC_FAULT_MESSAGE
//SERVICE_DI_DSC_OFF_LAMP
//SERVICE_DI_DSC_OFF_MESSAGE
//SERVICE_DI_TC_OFF_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_DSC_LAMP) = {
	DATA_ENTRY_FLASH( 12 , 0 , 4 , 0 , 2 ,ScsFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DSC_FAULT_MESSAGE) = {
		DATA_ENTRY( 12 , 4 , 1 , 0 , 1 ),
		DATA_ENTRY( 12 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_TC_FAULT_MESSAGE) = {
		DATA_ENTRY( 12 , 6 , 1 , 0 , 1 ),
		DATA_ENTRY( 12 , 7 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DSC_OFF_LAMP) = {
	DATA_ENTRY( 13 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DSC_OFF_MESSAGE) = {
	DATA_ENTRY( 13 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_TC_OFF_MESSAGE) = {
	DATA_ENTRY( 13 , 2 , 1 , 0 , 1 ),
};

//18.制动系统报警

//SERVICE_DI_BRAKE_SYSTEM_LAMP
//SERVICE_DI_BRAKE_SYSTEM_ECHO_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_BRAKE_SYSTEM_LAMP) = {
	DATA_ENTRY( 14 , 0 , 1 , 0 , 1),
};
__DECLARE_DATA_TABLE(SERVICE_DI_BRAKE_SYSTEM_ECHO_MESSAGE) = {
	DATA_ENTRY( 14 , 1 , 1 , 0 , 1 ),
	DATA_ENTRY( 14 , 2 , 1 , 0 , 1 ),
};

//19.安全带未系报警

//SERVICE_DI_SEAT_BELT_LAMP
//SERVICE_DI_SEAT_BELT_DRIVER_ECHO_MESSAGE
//SERVICE_DI_SEAT_BELT_PASSENGER_ECHO_MESSAGE
//SERVICE_DI_SEAT_BELT_WARNING_SOUND
__DECLARE_DATA_TABLE(SERVICE_DI_SEAT_BELT_LAMP) = {
	DATA_ENTRY_FLASH( 15 , 0 , 4 , 0 , 2 ,SeatBeltFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SEAT_BELT_DRIVER_ECHO_MESSAGE) = {
	DATA_ENTRY( 15 , 4 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SEAT_BELT_PASSENGER_ECHO_MESSAGE) = {
	DATA_ENTRY( 15 , 5 , 1 , 0 , 1),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SEAT_BELT_WARNING_SOUND) = {
	DATA_ENTRY( 15 , 6 , 2 , 0 , 2 ),
};

//20.SRS故障报警

//SERVICE_DI_SRS_LAMP
//SERVICE_DI_SRS_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_SRS_LAMP) = {
	DATA_ENTRY_FLASH( 16 , 0 , 4 , 0 , 2 , SrsFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SRS_ECHO_MESSAGE) = {
	DATA_ENTRY( 16 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 16 , 5 , 1 , 0 , 1 ),
};

//21.主大灯开指示
//SERVICE_DI_MAIN_BEAM_LAMP
//SERVICE_DI_MAIN_BEAM_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_MAIN_BEAM_LAMP) = {
	DATA_ENTRY( 17 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_MAIN_BEAM_ECHO_MESSAGE) = {
	DATA_ENTRY( 17 , 1 , 1 , 0 , 1 ),
};

//22.左转向指示报警
//SERVICE_DI_SERVICE_DIRECTION_INDICATOR_LEFT_HAND_LAMP
//SERVICE_DI_SERVICE_DIRECTION_INDICATOR_LEFT_HAND_LAMP_TICK_TOCK
//SERVICE_DI_SERVICE_DIRECTION_INDICATOR_RIGHT_HAND_LAMP
//SERVICE_DI_SERVICE_DIRECTION_INDICATOR_RIGHT_HAND_LAMP_TICK_TOCK

__DECLARE_DATA_TABLE(SERVICE_DI_DIRECTION_INDICATOR_LEFT_HAND_LAMP) = {
	DATA_ENTRY( 18 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DIRECTION_INDICATOR_LEFT_HAND_LAMP_TICK_TOCK) = {
	DATA_ENTRY( 18 , 1 , 2 , 0 , 2 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DIRECTION_INDICATOR_RIGHT_HAND_LAMP) = {
	DATA_ENTRY( 19 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DIRECTION_INDICATOR_RIGHT_HAND_LAMP_TICK_TOCK) = {
	DATA_ENTRY( 19 , 1 , 2 , 0 , 2 ),
};
//24.发动机防盗，钥匙电量低

//SERVICE_DI_VEHICLE_WITH_KEY_LAMP
//SERVICE_DI_ENGINE_SERVICE_DISABLED_MESSAGE
//SERVICE_DI_KEY_BATTERY_LOW_MESSAGE
//SERVICE_DI_ALARM_TRIGGERED_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_VEHICLE_WITH_KEY_LAMP) = {
	DATA_ENTRY_FLASH( 19 , 5 , 3 , 0 , 4 ,VehicleWithKeyLampFlash ),
};



__DECLARE_DATA_TABLE(SERVICE_DI_ENGINE_DISABLED_MESSAGE) = {
		DATA_ENTRY( 20 , 0 , 1 , 0 , 1 ),
		DATA_ENTRY( 20 , 1 , 1 , 0 , 1 ),
};


__DECLARE_DATA_TABLE(SERVICE_DI_KEY_BATTERY_LOW_MESSAGE) = {
		DATA_ENTRY( 20 , 2 , 1 , 0 , 1 ),
		DATA_ENTRY( 20 , 3 , 1 , 0 , 1 ),
};


__DECLARE_DATA_TABLE(SERVICE_DI_ALARM_TRIGGERED_MESSAGE) = {
	DATA_ENTRY( 20 , 4 , 1 , 0 ,1 ),
	DATA_ENTRY( 20 , 5 , 1 , 0 ,1 ),
};

//25.TCCM启动故障报警

//SERVICE_DI_TCCM_LAMP
//SERVICE_DI_TCCM_STATUS_ECHO_MESSAGE
//SERVICE_DI_TCCM_FAULT_ECHO_MESSAGE
//SERVICE_DI_TCCM_OVERHEATED_ECHO_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_TCCM_LAMP) = {
	DATA_ENTRY_FLASH( 21 , 0 , 4 , 0 , 3 ,TccmFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_TCCM_STATUS_ECHO_MESSAGE) = {
	DATA_ENTRY( 21 , 4 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_TCCM_FAULT_ECHO_MESSAGE) = {
	DATA_ENTRY( 21 , 5 , 1 , 0 , 1 ),
	DATA_ENTRY( 21 , 6 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_TCCM_OVERHEATED_ECHO_MESSAGE) = {
	DATA_ENTRY( 22 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 22 , 1 , 1 , 0 , 1 ),
};

//26.EPB状态

//SERVICE_DI_EPB_STATUS_LAMP
//SERVICE_DI_AUTOHOLD_FAULT_ECHO_MESSAGE
//SERVICE_DI_EPB_FAULT_LAMP
//SERVICE_DI_EPB_FAULT_ECHO_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_EPB_STATUS_LAMP) = {
	DATA_ENTRY_FLASH( 22 , 2 , 2 , 0 , 3 ,EpbStatusFlash ),
};

__DECLARE_DATA_TABLE(SERVICE_DI_AUTOHOLD_FAULT_ECHO_MESSAGE) = {
	DATA_ENTRY( 22 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 22 , 7 , 1 , 0 , 1 ),
};



__DECLARE_DATA_TABLE(SERVICE_DI_EPB_AUDIO) = {
	DATA_ENTRY( 22 , 5 , 2 , 0 , 3  ),
};


__DECLARE_DATA_TABLE(SERVICE_DI_EPB_FAULT_LAMP) = {
		DATA_ENTRY_FLASH( 23 , 0, 2 , 0 , 2 ,EpbFaultFlash),

};
__DECLARE_DATA_TABLE(SERVICE_DI_EPB_FAULT_ECHO_MESSAGE) = {
		DATA_ENTRY( 23 , 2, 1 , 0 , 1 ),
		DATA_ENTRY( 23 , 3, 1 , 0 , 1 ),
};
//28.低油量，油量信号错误

//SERVICE_DI_LOW_FUEL_LAMP
//SERVICE_DI_LOW_FUEL_ECHO_MESSAGE_LOW
//SERVICE_DI_FUEL_SIGNAL_ERROR_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_LOW_FUEL_LAMP) = {
	DATA_ENTRY_FLASH( 24 , 0 , 2 , 0 , 2, LowFuelFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_LOW_FUEL_ECHO_MESSAGE_LOW) = {
	DATA_ENTRY( 24 , 2 , 3 , 0 , 4 ),
	DATA_ENTRY( 24 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_FUEL_SIGNAL_ERROR_ECHO_MESSAGE) = {
	DATA_ENTRY( 24 , 6 , 1 , 0 , 1 ),
	DATA_ENTRY( 24 , 7 , 1 , 0 , 1 ),
};

//29.节能驾驶模式指示灯

//SERVICE_DI_ECO_LAMP
__DECLARE_DATA_TABLE(SERVICE_DI_ECO_LAMP) = {
	DATA_ENTRY( 25 , 0 , 1 , 0 , 1 ),
};


//30.近光灯指示
//SERVICE_DI_SERVICE_DIPPED_BEAM_LAMP
//SERVICE_DI_SERVICE_DIPPED_BEAM_LAMP_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_DIPPED_BEAM_LAMP) = {
	DATA_ENTRY( 26 , 0 , 2 , 0 , 2),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DIPPED_BEAM_LAMP_MESSAGE) = {
	DATA_ENTRY( 26 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 26 , 3 , 1 , 0 , 1 ),
};

//31.侧灯打开指示
//SERVICE_DI_LIGHT_ON_LAMP
//SERVICE_DI_SIDELIGHTS_ON_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_LIGHT_ON_LAMP) = {
	DATA_ENTRY( 27 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SIDELIGHTS_ON_ECHO_MESSAGE) = {
	DATA_ENTRY( 27 , 1 , 1 , 0 , 1 ),
};

//32.前雾灯指示
//SERVICE_DI_FRONT_FOG_LAMP
//SERVICE_DI_FRONT_FOG_ON_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_FRONT_FOG_LAMP) = {
	DATA_ENTRY( 28 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_FRONT_FOG_ON_ECHO_MESSAGE) = {
	DATA_ENTRY( 28 , 1 , 1 , 0 , 1 ),
};


//33.后雾灯指示
//SERVICE_DI_REAR_FOG_LAMP
//SERVICE_DI_REAR_FOG_ON_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_REAR_FOG_LAMP) = {
	DATA_ENTRY( 29 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_REAR_FOG_ON_ECHO_MESSAGE) = {
	DATA_ENTRY( 29 , 1 , 1 , 0 , 1 ),
};


//34.自动大灯指示
//SERVICE_DI_AUTO_MAIN_BEAM_LAMP
//SERVICE_DI_AUTO_MAIN_BEAM_ECHO_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_AUTO_MAIN_BEAM_LAMP) = {
	DATA_ENTRY( 30 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AUTO_MAIN_BEAM_ECHO_MESSAGE) = {
	DATA_ENTRY( 30 , 1 , 1 , 0 , 1 ),
};

//38.用钥匙启动报警

//SERVICE_DI_USE_KEY_TO_START_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_USE_KEY_TO_START_MESSAGE) = {
	DATA_ENTRY( 32 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 32 , 1 , 1 , 0 , 1 ),
};


//39.按下离合或制动要求
//SERVICE_DI_PRESS_CLUTCH_MESSAGE
//SERVICE_DI_PRESS_BRAKE_MESSAGE
//SERVICE_DI_NO_KEY_DETECTED_PRESS_CLUTCH_MESSAGE
//SERVICE_DI_NO_KEY_DETECTED_PRESS_BRAKE_MESSAGE
//SERVICE_DI_CLUTCH_SWITCH_FAULT_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_PRESS_CLUTCH_MESSAGE) = {
	DATA_ENTRY( 33 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 33 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_PRESS_BRAKE_MESSAGE) = {
	DATA_ENTRY( 33 , 2, 1 , 0 , 1 ),
	DATA_ENTRY( 33 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_NO_KEY_DETECTED_PRESS_CLUTCH_MESSAGE) = {
	DATA_ENTRY( 33 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 33 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_NO_KEY_DETECTED_PRESS_BRAKE_MESSAGE) = {
	DATA_ENTRY( 33 , 6 , 1 , 0 , 1 ),
	DATA_ENTRY( 33 , 7 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_CLUTCH_SWITCH_FAULT_MESSAGE) = {
	DATA_ENTRY( 34 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 34 , 1 , 1 , 0 , 1 ),
};

//40.关闭左前门请求
//SERVICE_DI_CLOSE_DRIVER_DOOR_TO_RESTART_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_CLOSE_DRIVER_DOOR_TO_RESTART_MESSAGE) = {
	DATA_ENTRY( 34 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 34 , 3 , 1 , 0 , 1 ),
};
//41.系好主驾安全带请求
//SERVICE_DI_FASTEN_SEATBELT_TO_RESTART_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_FASTEN_SEATBELT_TO_RESTART_MESSAGE) = {
	DATA_ENTRY( 35 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 35 , 1 , 1 , 0 , 1 ),
};

//42.选N请求（启停）
//SERVICE_DI_SELECT_NEUTRAL_TO_RESTART_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_SELECT_NEUTRAL_TO_RESTART_MESSAGE) = {
	DATA_ENTRY( 36 , 0 , 4 , 0 , 3 ),
	DATA_ENTRY( 36 , 4 , 1 , 0 , 1 ),
};

//43.停止启动/关闭指示
//SERVICE_DI_STOP_START_ON_MESSAGE
//SERVICE_DI_STOP_START_OFF_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_STOP_START_ON_MESSAGE) = {
	DATA_ENTRY( 37 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_STOP_START_OFF_MESSAGE) = {
	DATA_ENTRY( 37 , 1 , 1 , 0 , 1 ),
};

//44.自动驻车状态请求
//SERVICE_DI_AUTOHOLD_ASSIST1_MESSAGE
//SERVICE_DI_AUTOHOLD_ASSIST2_MESSAGE
//SERVICE_DI_AUTOHOLD_ASSIST3_MESSAGE
//SERVICE_DI_AUTOHOLD_ASSIST4_MESSAGE
//SERVICE_DI_AUTOHOLD_ASSIST5_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_AUTOHOLD_ASSIST1_MESSAGE) = {
	DATA_ENTRY( 38 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AUTOHOLD_ASSIST2_MESSAGE) = {
	DATA_ENTRY( 38 , 1 , 1 , 0 , 1 ),
	DATA_ENTRY( 38 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AUTOHOLD_ASSIST3_MESSAGE) = {
	DATA_ENTRY( 38 , 2 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AUTOHOLD_ASSIST4_MESSAGE) = {
	DATA_ENTRY( 38 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AUTOHOLD_ASSIST5_MESSAGE) = {
	DATA_ENTRY( 38 , 4 , 1 , 0 , 1 ),
};

//45.上坡辅助功能失效报警
//SERVICE_DI_HHC_FAIL_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_HHC_FAIL_MESSAGE) = {
	DATA_ENTRY( 39 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 39 , 1 , 1 , 0 , 1 ),

};

//46.锁状态指示
//SERVICE_DI_LOCK_STATUS_ON_MESSAGE
//SERVICE_DI_LOCK_STATUS_OFF_MESSAGE
//SERVICE_DI_LOCK_STATUS_FAIL_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_LOCK_STATUS_ON_MESSAGE) = {
	DATA_ENTRY( 40 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_LOCK_STATUS_OFF_MESSAGE) = {
	DATA_ENTRY( 40 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_LOCK_STATUS_FAIL_MESSAGE) = {
	DATA_ENTRY( 40 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 40 , 3 , 1 , 0 , 1 ),
};


//47.点火钥匙打开报警
//SERVICE_DI_IGNITION_KEY_ON_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_IGNITION_KEY_ON_MESSAGE) = {
	DATA_ENTRY( 41 ,0 , 1 , 0 , 1 ),
	DATA_ENTRY( 41 ,1 , 1 , 0 , 1 ),
};

//48.按键关闭发动机
//SERVICE_DI_PRESS_BUTTON_ENGINE_OFF_MESSAGE
//SERVICE_DI_LONG_PRESS_BUTTON_ENGINE_OFF_MESSAGE
//SERVICE_DI_DOUBLE_PRESS_BUTTON_ENGINE_OFF_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_PRESS_BUTTON_ENGINE_OFF_MESSAGE) = {
	DATA_ENTRY( 42 ,0 , 1 , 0 , 1 ),
	DATA_ENTRY( 42 ,1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_LONG_PRESS_BUTTON_ENGINE_OFF_MESSAGE) = {
	DATA_ENTRY( 42 ,2 , 1 , 0 , 1 ),
	DATA_ENTRY( 42 ,3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_DOUBLE_PRESS_BUTTON_ENGINE_OFF_MESSAGE) = {
	DATA_ENTRY( 42 ,4, 1 , 0 , 1 ),
	DATA_ENTRY( 42 ,5 , 1 , 0 , 1 ),
};

//49.按键制动转换请求
//SERVICE_DI_PRESS_BRAKE_SHIFT_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_PRESS_BRAKE_SHIFT_MESSAGE) = {
	DATA_ENTRY( 43 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 43 , 1 , 1 , 0 , 1 ),
};
//50.拔出钥匙请求
//SERVICE_DI_TAKE_SMART_KEY_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_TAKE_SMART_KEY_MESSAGE) = {
	DATA_ENTRY( 44 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 44 , 1 , 1 , 0 , 1 ),
};
//51.扳停车档请求
//SERVICE_DI_PUT_SHIFTER_TO_PARK_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_PUT_SHIFTER_TO_PARK_MESSAGE) = {
	DATA_ENTRY( 45 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 45 , 1 , 1 , 0 , 1 ),
};
//52.检测到无智能钥匙报警
//SERVICE_DI_NO_SMART_KEY_DETECTED_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_NO_SMART_KEY_DETECTED_MESSAGE) = {
	DATA_ENTRY( 46 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 46 , 1 , 1 , 0 , 1 ),
};
//53.把智能钥匙放到备用位置报警
//SERVICE_DI_PUT_KEY_INTO_BACKUP_POSITION_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_PUT_KEY_INTO_BACKUP_POSITION_MESSAGE) = {
	DATA_ENTRY( 47 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 47 , 1 , 1 , 0 , 1 ),
};

//54.点火继电器故障
//SERVICE_DI_IGNITION_RELAY_FAILED_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_IGNITION_RELAY_FAILED_MESSAGE) = {
	DATA_ENTRY( 48 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 48 , 1 , 1 , 0 , 1 ),
};

//55.启停按键失败报警
//SERVICE_DI_START_STOP_BUTTON_FAILED_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_START_STOP_BUTTON_FAILED_MESSAGE) = {
	DATA_ENTRY( 49 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 49 , 1 , 1 , 0 , 1 ),
};
//56.灯故障报警1
//SERVICE_DI_LEFT_BRAKE_LAMP_FAILED_MESSAGE
//SERVICE_DI_RIGHT_BRAKE_LAMP_FAILED_MESSAGE
//SERVICE_DI_LEFT_DI_LIGHT_FAILED_MESSAGE
//SERVICE_DI_RIGHT_DI_LIGHT_FAILED_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_LEFT_BRAKE_LAMP_FAILED_MESSAGE) = {
	DATA_ENTRY( 50 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 50 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_RIGHT_BRAKE_LAMP_FAILED_MESSAGE) = {
	DATA_ENTRY( 50 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 50 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_LEFT_DI_LIGHT_FAILED_MESSAGE) = {
	DATA_ENTRY( 50 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 50 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_RIGHT_DI_LIGHT_FAILED_MESSAGE) = {
	DATA_ENTRY( 50 , 6 , 1 , 0 , 1 ),
	DATA_ENTRY( 50 , 7 , 1 , 0 , 1 ),
};

//57.灯故障报警2
//SERVICE_DI_LEFT_DIPPED_BEAM_FAILED_MESSAGE
//SERVICE_DI_RIGHT_DIPPED_BEAM_FAILED_MESSAGE
//SERVICE_DI_FRONT_SIDE_LIGHT_FAILED_MESSAGE
//SERVICE_DI_REAR_SIDE_LIGHT_FAILED_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_LEFT_DIPPED_BEAM_FAILED_MESSAGE) = {
	DATA_ENTRY( 51 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 51 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_RIGHT_DIPPED_BEAM_FAILED_MESSAGE) = {
	DATA_ENTRY( 51 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 51 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_FRONT_SIDE_LIGHT_FAILED_MESSAGE) = {
	DATA_ENTRY( 51 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 51 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_REAR_SIDE_LIGHT_FAILED_MESSAGE) = {
	DATA_ENTRY( 51 , 6 , 1 , 0 , 1 ),
	DATA_ENTRY( 51 , 7 , 1 , 0 , 1 ),
};


//SERVICE_DI_LEFT_SIDE_LIGHT_FAILED_MESSAGE
//SERVICE_DI_RIGHT_SIDE_LIGHT_FAILED_MESSAGE
//SERVICE_DI_REAR_FOG_LIGHT_FAILED_MESSAGE
//SERVICE_DI_REVERSE_LAMP_FAILED_MESSAGE

__DECLARE_DATA_TABLE(SERVICE_DI_LEFT_SIDE_LIGHT_FAILED_MESSAGE) = {
	DATA_ENTRY( 52 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 52 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_RIGHT_SIDE_LIGHT_FAILED_MESSAGE) = {
	DATA_ENTRY( 52 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 52 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_REAR_FOG_LIGHT_FAILED_MESSAGE) = {
	DATA_ENTRY( 52 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 52 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_REVERSE_LAMP_FAILED_MESSAGE) = {
	DATA_ENTRY( 52 , 6 , 1 , 0 , 1 ),
	DATA_ENTRY( 52 , 7 , 1 , 0 , 1 ),
};


//SERVICE_DI_DAY_TIME_RUNNING_LAMP_FAILED_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_DAY_TIME_RUNNING_LAMP_FAILED_MESSAGE) = {
	DATA_ENTRY( 53 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 53 , 1 , 1 , 0 , 1 ),
};


//58.钥匙拔出指示灯报警
//SERVICE_DI_LIGHTS_ON_KEY_OUT_WARNING_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_LIGHTS_ON_KEY_OUT_WARNING_MESSAGE) = {
	DATA_ENTRY( 54 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 54 , 1 , 1 , 0 , 1 ),
};

//59.清洗液刷水位低报警
//SERVICE_DI_LOW_WASHER_FLUID_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_LOW_WASHER_FLUID_MESSAGE) = {
	DATA_ENTRY( 55 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 55 , 1 , 1 , 0 , 1 ),
};

//60.窗口打开提示
//SERVICE_DI_DRIVER_WINDOW_OPEN_ECHO_MESSAGE
//SERVICE_DI_FRONT_PASSENGER_WINDOW_OPEN_ECHO_MESSAGE
//SERVICE_DI_REAR_LEFT_WINDOW_OPEN_ECHO_MESSAGE
//SERVICE_DI_REAR_RIGHT_WINDOW_OPEN_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_DRIVER_WINDOW_OPEN_ECHO_MESSAGE) = {
	DATA_ENTRY( 56 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 56 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_FRONT_PASSENGER_WINDOW_OPEN_ECHO_MESSAGE) = {
	DATA_ENTRY( 56 , 2 , 1 , 0 , 1 ),
	DATA_ENTRY( 56 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_REAR_LEFT_WINDOW_OPEN_ECHO_MESSAGE) = {
	DATA_ENTRY( 56 , 4 , 1 , 0 , 1 ),
	DATA_ENTRY( 56 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_REAR_RIGHT_WINDOW_OPEN_ECHO_MESSAGE) = {
	DATA_ENTRY( 56 , 6 , 1 , 0 , 1 ),
	DATA_ENTRY( 56 , 7 , 1 , 0 , 1 ),
};


//SERVICE_DI_SUNROOF_OPEN_ECHO_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_SUNROOF_OPEN_ECHO_MESSAGE) = {
	DATA_ENTRY( 57 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 57 , 1 , 1 , 0 , 1 ),
};

//61.功能配置/用户信息设置

//SERVICE_DI_CONFIG_FUNCTION_ACTIVE_SAFETY
//SERVICE_DI_CONFIG_FUNCTION_MEDIA
//SERVICE_DI_CONFIG_FUNCTION_COMMUNICATION
//SERVICE_DI_CONFIG_FUNCTION_REVERSING_CAMERA
//SERVICE_DI_CONFIG_FUNCTION_TAB_INDEX
__DECLARE_DATA_TABLE(SERVICE_DI_CONFIG_FUNCTION_ACTIVE_SAFETY) = {
	DATA_ENTRY( 58 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_CONFIG_FUNCTION_MEDIA) = {
	DATA_ENTRY( 58 , 1 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_CONFIG_FUNCTION_COMMUNICATION) = {
	DATA_ENTRY( 58 , 2 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_CONFIG_FUNCTION_REVERSING_CAMERA) = {
	DATA_ENTRY( 58 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_CONFIG_FUNCTION_TAB_INDEX) = {
	DATA_ENTRY( 58 , 4 , 3 , 0 , 6 ),
};

//62.EPB辅助报警

//SERVICE_DI_EPB_ASSIST1_MESSAGE
//SERVICE_DI_EPB_ASSIST2_MESSAGE
//SERVICE_DI_EPB_ASSIST3_MESSAGE
//SERVICE_DI_EPB_ASSIST4_MESSAGE
//SERVICE_DI_EPB_ASSIST5_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_EPB_ASSIST1_MESSAGE) = {
	DATA_ENTRY( 59 , 0 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_EPB_ASSIST2_MESSAGE) = {
	DATA_ENTRY( 59 , 1 , 1 , 0 , 1 ),
	DATA_ENTRY( 59 , 5 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_EPB_ASSIST3_MESSAGE) = {
	DATA_ENTRY( 59 , 2 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_EPB_ASSIST4_MESSAGE) = {
	DATA_ENTRY( 59 , 3 , 1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_EPB_ASSIST5_MESSAGE) = {
	DATA_ENTRY( 59 , 4 , 1 , 0 , 1 ),
};

//63.AFS故障报警

// SERVICE_DI_AFS_FAULT_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_AFS_FAULT_MESSAGE) = {
	DATA_ENTRY( 60 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 60 , 1 , 1 , 0 , 1 ),
};

//64.电池故障报警

//SERVICE_DI_BATTERY_FAIL_MESSAGE
__DECLARE_DATA_TABLE(SERVICE_DI_BATTERY_FAIL_MESSAGE) = {
	DATA_ENTRY( 61 , 0 , 1 , 0 , 1 ),
	DATA_ENTRY( 61 , 1 , 1 , 0 , 1 ),
};

__DECLARE_DATA_TABLE( SERVICE_DI_GEARBOX_OVERHEAT_MESSAGE ) = {
    DATA_ENTRY( 62 , 0 , 3 , 0 , 5 ),
    DATA_ENTRY( 62 , 3 , 2 , 0 , 2 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_OVERSPEED_WARNING_MESSAGE ) = {
    DATA_ENTRY( 63 , 0 , 1 , 0 , 1 ),
    DATA_ENTRY( 63 , 2 , 1 , 0 , 1 )
};

__DECLARE_DATA_TABLE( SERVICE_DI_OVER_SPEED_WARNING_LAMP_HALFHZ ) = {
    DATA_ENTRY_FLASH( 63 , 1 , 1 , 0 , 1 , OverSpeedWarningFlash ) 
};

__DECLARE_DATA_TABLE( SERVICE_DI_PDC_SYSTEM_FAILED_MESSAGE ) = {
    DATA_ENTRY( 64 , 0 , 1 , 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_PDC_STATUS_SOUND ) = {
    DATA_ENTRY( 64 , 1 , 2 , 0 , 2 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_FL_TYRE_LOW_MESSAGE ) = {
    DATA_ENTRY( 65 , 0 , 1 , 0 , 1 ),
    DATA_ENTRY( 65 , 1 , 1 , 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_FR_TYRE_LOW_MESSAGE ) = {
    DATA_ENTRY( 65 , 2 , 1 , 0 ,1 ),
    DATA_ENTRY( 65 , 3 , 1 , 0 ,1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_RL_TYRE_LOW_MESSAGE ) = {
    DATA_ENTRY( 65 , 4 , 1, 0 , 1 ),
    DATA_ENTRY( 65 , 5 , 1, 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_RR_TYRE_LOW_MESSAGE ) = {
    DATA_ENTRY( 65 , 6 , 1 , 0 ,1 ),
    DATA_ENTRY( 65 , 7 , 1 , 0 ,1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_ENGAGE_PARK_OR_NEUTRAL_TO_START_MESSAGE ) = {
    DATA_ENTRY( 66 , 0 ,1 , 0 , 1),
    DATA_ENTRY( 66 , 1 ,1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_INITIALIZE_DRIVER_WINDOW_MESSAGE ) = {
    DATA_ENTRY( 67 , 0 , 1 , 0 , 1 ),
    DATA_ENTRY( 67 , 1 , 1 , 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_PEPS_ANTENNA_FAULT_MESSAGE ) = {
    DATA_ENTRY( 68 , 0 , 1 , 0 , 1),
    DATA_ENTRY( 68 , 1 , 1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_SEAT_POSITION_MEMORY_SET_SUCCESS_MESSAGE ) = {
    DATA_ENTRY( 69 , 0 ,1 , 0 ,1 ),
    DATA_ENTRY( 69 , 1 ,1 , 0 ,1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_POWER_LIFTGATE_SYSTEM_FAULT_MESSAGE ) = {
    DATA_ENTRY( 70 , 0 , 1 , 0 , 1),
    DATA_ENTRY( 70 , 1 , 1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_POWER_LIFTGATE_SYSTEM_LIMIT_MESSAGE ) = {
    DATA_ENTRY( 70 , 2 , 1 , 0 , 1 ),
    DATA_ENTRY( 70 , 3 , 1 , 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_POWER_LIFTGATE_PUT_IN_PARK_REQUEST_MESSAGE ) = {
    DATA_ENTRY( 70 , 4, 1 , 0 , 1 ),
    DATA_ENTRY( 70 , 5, 1 , 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_POWER_LIFTGATE_MANUAL_CLOSE_REQUEST_MESSAGE ) = {
    DATA_ENTRY( 70 , 6 , 1 , 0 , 1),
    DATA_ENTRY( 70 , 6 , 1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_SIA_REMINDER_SUGGEST_MESSAGE ) = {
    DATA_ENTRY( 71 , 0 , 1 , 0 , 1),
    DATA_ENTRY( 71 , 1 , 1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_FICM_SIA_REMINDER_SUGGEST_MESSAGE ) = {
    DATA_ENTRY( 71 , 2 , 1 , 0 , 1 ),
    DATA_ENTRY( 71 , 3 , 1 , 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_FICM_SIA_REMINDER_IMMEDIATELY_MESSAGE ) = {
    DATA_ENTRY( 71, 4 , 1 , 0 , 1),
    DATA_ENTRY( 71, 5 , 1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_IPK_OVERHEATING_MESSGE ) = {
    DATA_ENTRY( 72 , 0 , 1, 0 , 1),
    DATA_ENTRY( 72 , 1 , 1, 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_LEFT_REGULATE_STREERING_MESSAGE ) = {
    DATA_ENTRY( 73 , 0 ,1 ,0 , 1),
    DATA_ENTRY( 73 , 1 ,1 ,0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_RIGHT_REGULATE_STEERING_MESSAGE ) = {
    DATA_ENTRY( 73 , 2 , 1, 0 , 1),
    DATA_ENTRY( 73 , 3 , 1, 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_KEY_OFF_WHEEL_NOT_STRAIGHT_REMINDER_MESSAGE ) = {
    DATA_ENTRY( 73 , 4 , 1 , 0 , 1),
    DATA_ENTRY( 73 , 5 , 1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_NAVIGATION_ABNORMAL_DISPLAY ) = {
    DATA_ENTRY( 74 , 0 , 1 , 0 , 1 )
};
__DECLARE_DATA_TABLE( SERVICE_DI_VIDEO_ABNORMAL_DISPLAY ) = {
    DATA_ENTRY( 74 , 1 , 1 , 0 , 1)
};
__DECLARE_DATA_TABLE( SERVICE_DI_TELEPHONE_ABNORMAL_DISPLAY ) = {
    DATA_ENTRY( 74 , 2 , 1 , 0 , 1 )
};

__DECLARE_DATA_TABLE( SERVICE_DI_RVC ) = {
    DATA_ENTRY( 74 , 3 , 1 , 0 , 1 )
};

__DECLARE_DATA_TABLE( SERVICE_DI_NEXT_MAINTENANCE_DATE ) = {
    DATA_ENTRY( 77 , 0 , 8 , 0 , 0xff),/*year*/
    DATA_ENTRY( 78 , 0 , 8 , 0 , 0xff),/*month*/
    DATA_ENTRY( 79 , 0 , 8 , 0 , 0xff),/*day*/
};

__DECLARE_DATA_TABLE( SERVICE_DI_ANGULAR_CONFIGURATION_OF_ROTATIONAL_SPEED ) = {
    DATA_ENTRY( 81 , 0 , 8 , 0 , 0xff )
};

__DECLARE_DATA_TABLE( SERVICE_DI_USER_TIME_STANDARD ) = {
    DATA_ENTRY( 82 , 0 , 1 , 0 , 1)
};

__DECLARE_DATA_TABLE( SERVICE_DI_USER_TIME_FORMAT ) = {
    DATA_ENTRY( 82 , 1 , 1 , 0 , 1)
};

__DECLARE_DATA_TABLE( SERVICE_DI_USER_LANGUAGE_SETTING ) = {
    DATA_ENTRY( 82 , 2 , 1 , 0 , 1)
};

__DECLARE_DATA_TABLE( SERVICE_DI_USER_ODO_UNIT ) = {
    DATA_ENTRY( 82 , 3 , 1 , 0 , 1)
};

__DECLARE_DATA_TABLE( SERVICE_DI_USER_TEMPERATURE_UNIT ) = {
    DATA_ENTRY( 82 , 4 , 1 , 0 , 1)
};

__DECLARE_DATA_TABLE( SERVICE_DI_USER_FUEL_CONSUMPTION_UNIT ) = {
    DATA_ENTRY( 82 , 5 , 2 , 0 , 2 )
};


///#define CONFIG_ADAS 1
///#define CONFIG_ACC 1
///#define CONFIG_AEB 1
///#define CONFIG_LDW 1
///#define CONFIG_FCW 1 
///#define CONFIG_SAS 1

#ifdef CONFIG_ADAS
/*84*/
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SYSTEM_FAULT_LAMP ) = {
	DATA_ENTRY( 83 , 0 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE( SETVICE_DI_ACC_SYSTEM_ACTIVE_GREEN_LAMP ) = {
	DATA_ENTRY( 83 , 1 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SYSTEM_STAND_BY_YELLOW_LAMP ) = {
	DATA_ENTRY( 83 , 2 ,  1 , 0 , 1 ),
};
	
	
/*85*/	
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SYSTEM_STAND_BY_MESSAGE ) = {
	DATA_ENTRY( 84 , 0 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_TAKE_OVER_MESSAGE ) = {
	DATA_ENTRY( 84 , 1 ,  1 , 0 , 1 ),
	DATA_ENTRY( 84 , 2 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SENSOR_BLOCK_MESSAGE ) = {
	DATA_ENTRY( 84 , 3 ,  1 , 0 , 1 ),
	DATA_ENTRY( 84 , 4 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SYSTEM_CANCEL_REQUEST_MESSAGE ) = {
	DATA_ENTRY( 84 , 5 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SYSTEM_UNAVAILABLE_MESSAGE ) = {
	DATA_ENTRY( 84 , 6 ,  1 , 0 , 1 ),
	DATA_ENTRY( 84 , 7 ,  1 , 0 , 1 ),
};

	
/*86*/
	__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SYSTEM_OFF_MESSAGE) = {
	DATA_ENTRY( 85 , 0 ,  1 , 0 , 1 ),
};
	__DECLARE_DATA_TABLE( SERVICE_DI_ACC_SYSTEM_ON_MESSAGE) = {
	DATA_ENTRY( 85 , 1 ,  1 , 0 , 1 ),
};
	__DECLARE_DATA_TABLE( SERVICE_DI_ACC_DRIVER_SELECT_TARGET_SPEED_ENABLE) = {
	DATA_ENTRY( 85 , 2 ,  1 , 0 , 1 ),
};
	__DECLARE_DATA_TABLE( SERVICE_DI_ACC_CAR_TYPE0) = {
	DATA_ENTRY( 85 , 4 ,  1 , 0 , 1 ),
};
	__DECLARE_DATA_TABLE( SERVICE_DI_ACC_CAR_TYPE1) = {
	DATA_ENTRY( 85 , 5 ,  1 , 0 , 1 ),
};
	__DECLARE_DATA_TABLE( SERVICE_DI_ACC_CAR_TYPE2) = {
	DATA_ENTRY( 85 , 6 ,  1 , 0 , 1 ),
};
	__DECLARE_DATA_TABLE( SERVICE_DI_FRONT_CAR_DISAPPEARED) = {
	DATA_ENTRY( 85 , 7 ,  1 , 0 , 1 ),
};
	
	/*87*/
__DECLARE_DATA_TABLE( SERVICE_DI_FRONT_CAR_ON_POSITION ) = {
	DATA_ENTRY( 86 , 0 ,  3 , 0 , 7 ),
};	
__DECLARE_DATA_TABLE( SERVICE_DI_TIME_DISTANCE_DISAPPEARED ) = {
	DATA_ENTRY( 86 , 4 ,  1 , 0 , 1 ),
};
	
/*88*/
	__DECLARE_DATA_TABLE( SERVICE_DI_TIME_DISTANCE_POSITION_COLOR) = {
	DATA_ENTRY( 87 , 0 ,  8 , 0 , 255 ),
};

	/*89*/
__DECLARE_DATA_TABLE( SERVICE_DI_FVCM_FAULT_MESSASGE) = {
	DATA_ENTRY( 88 , 0 ,  1 , 0 , 1 ),
	DATA_ENTRY( 88 , 1 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE( SERVICE_DI_ADAS_TAB_JUMP_REQUEST) = {
	DATA_ENTRY( 88 , 3 ,  1 , 0 , 1 ),
};


/*90*/
__DECLARE_DATA_TABLE( SERVICE_DI_ACC_DRIVER_SELECT_TARGET_SPEED ) = {
	DATA_ENTRY( 89 , 0 ,  8 , 0 , 240 ),
};
	

/*91*/
	__DECLARE_DATA_TABLE( SERVICE_DI_ACC_FUNCTION_NOT_AVAIBLE) = {
	DATA_ENTRY( 90 , 0 ,  1 , 0 , 1 ),
};



__DECLARE_DATA_TABLE( SERVICE_DI_DRIVER_SELECT_TARGET_DISTANCE_LEVEL) = {
	DATA_ENTRY( 90 , 1 ,  3 , 0 , 7 ),
	DATA_ENTRY( 86 , 4 ,  1 , 0 , 1 ),
};
	/*92*/
	/*93*/
	/*94*/
	/*95*/
struct FlashAttr AebFaultFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 0 , 1000 , 1 , 1000 )  ,
    
    FLASH_RESET()  
};
__DECLARE_DATA_TABLE(SERVICE_DI_AEB_SYSTEM_OFF_LAMP)= {
	DATA_ENTRY(94 , 0 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AEB_SYSTEM_FAULT_FLASH)= {
	DATA_ENTRY_FLASH(94 , 1 ,  1 , 0 , 1 , AebFaultFlash ),
};
	
	/*96*/	
__DECLARE_DATA_TABLE(SERVICE_DI_AEB_SYSTEM_UNAVAILABE_MESSAGE)= {
	DATA_ENTRY(95 , 0 ,  1 , 0 , 1 ),
	DATA_ENTRY(95 , 1 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AEB_SYSTEM_OFF_MESSAGE)= {
	DATA_ENTRY(95 , 2 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AEB_SYSTEM_ON_MESSAGE)= {
	DATA_ENTRY(95 , 3 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_AEB_ACTIVE_MESSAGE)= {
	DATA_ENTRY(95 , 4 ,  1 , 0 , 1 ),
};

	/*97*/
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_ACTIVE_LAMP_GREEN)= {
	DATA_ENTRY(96 , 0 ,  1 , 0 , 1 ),
};

struct FlashAttr LdwFaultFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 0 , 1000 , 1 , 1000 )  ,
    
    FLASH_RESET()  
};
    
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_FAULT_LAMP_YELLOW)= {
	DATA_ENTRY_FLASH(96 , 1 ,  1 , 0 , 1 , LdwFaultFlash ),
}; 


__DECLARE_DATA_TABLE(SERVICE_DI_LDW_OFF_LAMP_YELLOW)= {
	DATA_ENTRY(96 , 2 ,  1 , 0 , 1 ),
};

/*98*/
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_SYSTEM_OFF_ECHO_MESSAGE)= {
	DATA_ENTRY(97 , 0 ,  1 , 0 , 1 ),
	DATA_ENTRY(97 , 1 ,  1 , 0 , 1 ),
	};
	
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_STAND_BY_ECHO_MESSAGE)= {
	DATA_ENTRY(97 , 2 ,  1 , 0 , 1 ),
	};
	
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_CAR_TYPE0)= {
	DATA_ENTRY(97 , 3 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_CAR_TYPE1)= {
	DATA_ENTRY(97 , 4 ,  1 , 0 , 1 ),
	};
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_CAR_TYPE2)= {
	DATA_ENTRY(97 , 5 ,  1 , 0 , 1 ),
	};
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_LANES_DISPLAY)= {
	DATA_ENTRY(97 , 6 ,  1 , 0 , 1 ),
	};
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_AUDIBLE_WARNING_SPECIAL_GONG)= {
	DATA_ENTRY(97 , 7 ,  1 , 0 , 1 ),
	};

	/*99*/
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_SYSTEM_CROSSING_LANE_MESSAGE)= {
	DATA_ENTRY(98 , 0 ,  1 , 0 , 1 ),
	};
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_UNAVAILABLE_MESSAGE)= {
	DATA_ENTRY(98 , 1 ,  1 , 0 , 1 ),
	};
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_LEFT_LANE_STATUS)= {
	DATA_ENTRY(98 , 2 ,  3 , 0 , 7 ),
	};
__DECLARE_DATA_TABLE(SERVICE_DI_LDW_RIGHT_LANE_STATUS)= {
	DATA_ENTRY(98 , 5 ,  3 , 0 , 7 ),
	};


	/*100*/
struct FlashAttr FcwFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 0 , 1000 , 1 , 1000 )  ,
    
    FLASH_RESET()  
};

__DECLARE_DATA_TABLE(SERVICE_DI_FCW_SYSTEM_OFF_LAMP)= {
	DATA_ENTRY(99 , 0 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_FCW_SYSTEM_FAULT_LAMP_FLASH)= {
	DATA_ENTRY_FLASH(99 , 1 ,  1 , 0 , 1 , FcwFlash ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_FCW_SYSTEM_OFF_ECHO_MESSAGE) = {
	DATA_ENTRY(99 , 6 ,  1 , 0 , 1 ),	
};
__DECLARE_DATA_TABLE(SERVICE_DI_FCW_SYSTEM_ON_ECHO_MESSAGE) = {
	DATA_ENTRY(99 , 7 ,  1 , 0 , 1 ),
};	
	
	/*101*/	
__DECLARE_DATA_TABLE(SERVICE_DI_FCW_WARNING_ECHO_MESSAGE) = {
	DATA_ENTRY(100 , 0 ,  1 , 0 , 1 ),
	DATA_ENTRY(100 , 1 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_FCW_SYSTEM_UNAVAILABLE_ECHO_MESSAGE) = {
	DATA_ENTRY(100 , 2 ,  1 , 0 , 1 ),
	DATA_ENTRY(100 , 3 ,  2 , 0 , 2 ),
};

	/*102*/
struct FlashAttr SasYellowFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 0 , 1000 , 1 , 1000 )  ,
    
    FLASH_RESET()  
};
struct FlashAttr SasGreenFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 0 , 500 , 1 , 500 )  ,
    
    FLASH_RESET()  
};
struct FlashAttr SasSpeedFlash[] = {
    FLASH_OFF(),
    FLASH_ON( -1 , 0 , 1000 , 1 , 1000 )  ,
    
    FLASH_RESET()  
};

__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_YELLOW_LAMP_FLASH_AT_HALFHZ) = {
	DATA_ENTRY_FLASH(101 , 0 ,  1 , 0 , 1 , SasYellowFlash),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_YELLOW_LAMP) = {
	DATA_ENTRY(101 , 1 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_GREEN_LAMP_FLASH_AT_ONEHZ) = {
	DATA_ENTRY_FLASH(101 , 2 ,  1 , 0 , 1 , SasGreenFlash),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_GREEN_LAMP) = {
	DATA_ENTRY(101 , 3 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_SPEED_LAMP) = {
	DATA_ENTRY(101 , 4 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_SPEED_LAMP_SPEED_VALUE_FLASH_AT_HALFHZ) = {
	DATA_ENTRY_FLASH(101 , 5 ,  1 , 0 , 1 , SasSpeedFlash ),
};
	
	/*103*/
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_FAULT_MESSAGE) = {
	DATA_ENTRY(102 , 0 ,  1 , 0 , 1 ),
	DATA_ENTRY(102 , 1 ,  1 , 0 , 1 ),
};
__DECLARE_DATA_TABLE(SERVICE_DI_SAS_SYSTEM_SPEED_LIMIT_REMINDER_MESSAGE) = {
	DATA_ENTRY(102 , 2 ,  1 , 0 , 1 ),
};

#endif





struct MsgAttr SpecialMsgTable[] = {
    __DECLARE_MSG_ENTRY( SERVICE_DI_CRUISE_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CRUISE_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ENGINE_COOLANT_TEMP_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ENGINE_COOLANT_TEMP_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DRIVE_BY_WIRE_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DRIVE_BY_WIRE_LAMP_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_MIL_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_MIL_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ALTERNATOR_CHARGE_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ALTERNATOR_CHARGE_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SHED_LEVEL_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_OIL_PRESSURE_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_OIL_PRESSURE_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_STOP_START_ACTIVE_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_STOP_START_ACTIVE_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_STOP_START_FAULT_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_STOP_START_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_STEERING_WHEEL_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPS_FAULT_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SAS_FAULT_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SAS_UNCALIBRATION_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TPMS_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TPMS_WARN_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TPMS_SYSTEM_FAIL_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ABS_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ABS_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_HDC_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_HDC_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DSC_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DSC_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TC_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DSC_OFF_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DSC_OFF_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TC_OFF_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_BRAKE_SYSTEM_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_BRAKE_SYSTEM_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SEAT_BELT_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SEAT_BELT_DRIVER_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SEAT_BELT_PASSENGER_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SEAT_BELT_WARNING_SOUND , target_aud ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SRS_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SRS_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_MAIN_BEAM_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_MAIN_BEAM_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DIRECTION_INDICATOR_LEFT_HAND_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DIRECTION_INDICATOR_LEFT_HAND_LAMP_TICK_TOCK , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DIRECTION_INDICATOR_RIGHT_HAND_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DIRECTION_INDICATOR_RIGHT_HAND_LAMP_TICK_TOCK , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_VEHICLE_WITH_KEY_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ENGINE_DISABLED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_KEY_BATTERY_LOW_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ALARM_TRIGGERED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TCCM_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TCCM_STATUS_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TCCM_FAULT_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TCCM_OVERHEATED_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_STATUS_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTOHOLD_FAULT_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_AUDIO , target_aud ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_FAULT_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_FAULT_ECHO_MESSAGE , target_aud ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LOW_FUEL_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LOW_FUEL_ECHO_MESSAGE_LOW , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FUEL_SIGNAL_ERROR_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ECO_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DIPPED_BEAM_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DIPPED_BEAM_LAMP_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LIGHT_ON_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SIDELIGHTS_ON_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FRONT_FOG_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FRONT_FOG_ON_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_REAR_FOG_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_REAR_FOG_ON_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTO_MAIN_BEAM_LAMP , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTO_MAIN_BEAM_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_USE_KEY_TO_START_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PRESS_CLUTCH_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PRESS_BRAKE_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_NO_KEY_DETECTED_PRESS_CLUTCH_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_NO_KEY_DETECTED_PRESS_BRAKE_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CLUTCH_SWITCH_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CLOSE_DRIVER_DOOR_TO_RESTART_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FASTEN_SEATBELT_TO_RESTART_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SELECT_NEUTRAL_TO_RESTART_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_STOP_START_ON_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_STOP_START_OFF_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTOHOLD_ASSIST1_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTOHOLD_ASSIST2_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTOHOLD_ASSIST3_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTOHOLD_ASSIST4_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AUTOHOLD_ASSIST5_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_HHC_FAIL_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LOCK_STATUS_ON_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LOCK_STATUS_OFF_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LOCK_STATUS_FAIL_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_IGNITION_KEY_ON_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PRESS_BUTTON_ENGINE_OFF_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LONG_PRESS_BUTTON_ENGINE_OFF_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DOUBLE_PRESS_BUTTON_ENGINE_OFF_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PRESS_BRAKE_SHIFT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TAKE_SMART_KEY_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PUT_SHIFTER_TO_PARK_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_NO_SMART_KEY_DETECTED_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PUT_KEY_INTO_BACKUP_POSITION_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_IGNITION_RELAY_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_START_STOP_BUTTON_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LEFT_BRAKE_LAMP_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RIGHT_BRAKE_LAMP_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LEFT_DI_LIGHT_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RIGHT_DI_LIGHT_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LEFT_DIPPED_BEAM_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RIGHT_DIPPED_BEAM_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FRONT_SIDE_LIGHT_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_REAR_SIDE_LIGHT_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LEFT_SIDE_LIGHT_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RIGHT_SIDE_LIGHT_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_REAR_FOG_LIGHT_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_REVERSE_LAMP_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DAY_TIME_RUNNING_LAMP_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LIGHTS_ON_KEY_OUT_WARNING_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LOW_WASHER_FLUID_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_DRIVER_WINDOW_OPEN_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FRONT_PASSENGER_WINDOW_OPEN_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_REAR_LEFT_WINDOW_OPEN_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_REAR_RIGHT_WINDOW_OPEN_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SUNROOF_OPEN_ECHO_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CONFIG_FUNCTION_ACTIVE_SAFETY , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CONFIG_FUNCTION_MEDIA , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CONFIG_FUNCTION_COMMUNICATION , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CONFIG_FUNCTION_REVERSING_CAMERA , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_CONFIG_FUNCTION_TAB_INDEX , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_ASSIST1_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_ASSIST2_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_ASSIST3_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_ASSIST4_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_EPB_ASSIST5_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_AFS_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_BATTERY_FAIL_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_GEARBOX_OVERHEAT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_OVERSPEED_WARNING_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_OVER_SPEED_WARNING_LAMP_HALFHZ , target_background ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PDC_SYSTEM_FAILED_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PDC_STATUS_SOUND , target_aud ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FL_TYRE_LOW_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FR_TYRE_LOW_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RL_TYRE_LOW_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RR_TYRE_LOW_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ENGAGE_PARK_OR_NEUTRAL_TO_START_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_INITIALIZE_DRIVER_WINDOW_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_PEPS_ANTENNA_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SEAT_POSITION_MEMORY_SET_SUCCESS_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_POWER_LIFTGATE_SYSTEM_FAULT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_POWER_LIFTGATE_SYSTEM_LIMIT_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_POWER_LIFTGATE_PUT_IN_PARK_REQUEST_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_POWER_LIFTGATE_MANUAL_CLOSE_REQUEST_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_SIA_REMINDER_SUGGEST_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FICM_SIA_REMINDER_SUGGEST_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_FICM_SIA_REMINDER_IMMEDIATELY_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_IPK_OVERHEATING_MESSGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_LEFT_REGULATE_STREERING_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RIGHT_REGULATE_STEERING_MESSAGE , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_KEY_OFF_WHEEL_NOT_STRAIGHT_REMINDER_MESSAGE , target_app/*_pwr*/ ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_NAVIGATION_ABNORMAL_DISPLAY , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_VIDEO_ABNORMAL_DISPLAY , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_TELEPHONE_ABNORMAL_DISPLAY , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_RVC , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_NEXT_MAINTENANCE_DATE , target_tabicon ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_ANGULAR_CONFIGURATION_OF_ROTATIONAL_SPEED , target_app ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_USER_TIME_STANDARD , target_tabicon ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_USER_TIME_FORMAT , target_tabicon ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_USER_LANGUAGE_SETTING , target_tabicon ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_USER_ODO_UNIT , target_tabicon ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_USER_TEMPERATURE_UNIT , target_tabicon ),
    __DECLARE_MSG_ENTRY( SERVICE_DI_USER_FUEL_CONSUMPTION_UNIT , target_tabicon ),
    
 

 
 
#ifdef CONFIG_ADAS

#ifdef CONFIG_ACC
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SYSTEM_FAULT_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SETVICE_DI_ACC_SYSTEM_ACTIVE_GREEN_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SYSTEM_STAND_BY_YELLOW_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SYSTEM_STAND_BY_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_TAKE_OVER_MESSAGE,target_app), 
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SENSOR_BLOCK_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SYSTEM_CANCEL_REQUEST_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SYSTEM_UNAVAILABLE_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SYSTEM_OFF_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_SYSTEM_ON_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_DRIVER_SELECT_TARGET_SPEED_ENABLE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_CAR_TYPE0,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_CAR_TYPE1,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_CAR_TYPE2,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FRONT_CAR_DISAPPEARED,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FRONT_CAR_ON_POSITION,target_app),
	//__DECLARE_MSG_ENTRY( SERVICE_DI_TIME_DISTANCE_DISAPPEARED,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_TIME_DISTANCE_POSITION_COLOR,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FVCM_FAULT_MESSASGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ADAS_TAB_JUMP_REQUEST,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_DRIVER_SELECT_TARGET_SPEED,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_ACC_FUNCTION_NOT_AVAIBLE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_DRIVER_SELECT_TARGET_DISTANCE_LEVEL,target_app),
#endif

#ifdef CONFIG_AEB
	__DECLARE_MSG_ENTRY( SERVICE_DI_AEB_SYSTEM_OFF_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_AEB_SYSTEM_FAULT_FLASH,target_app),	
	__DECLARE_MSG_ENTRY( SERVICE_DI_AEB_SYSTEM_UNAVAILABE_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_AEB_SYSTEM_OFF_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_AEB_SYSTEM_ON_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_AEB_ACTIVE_MESSAGE,target_app),
#endif

#ifdef CONFIG_LDW
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_ACTIVE_LAMP_GREEN,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_FAULT_LAMP_YELLOW,target_app), 
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_OFF_LAMP_YELLOW,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_SYSTEM_OFF_ECHO_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_STAND_BY_ECHO_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_CAR_TYPE0,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_CAR_TYPE1,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_CAR_TYPE2,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_LANES_DISPLAY,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_AUDIBLE_WARNING_SPECIAL_GONG,target_aud),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_SYSTEM_CROSSING_LANE_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_UNAVAILABLE_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_LEFT_LANE_STATUS,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_LDW_RIGHT_LANE_STATUS,target_app),
#endif

#ifdef CONFIG_FCW
	__DECLARE_MSG_ENTRY( SERVICE_DI_FCW_SYSTEM_OFF_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FCW_SYSTEM_FAULT_LAMP_FLASH,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FCW_SYSTEM_OFF_ECHO_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FCW_SYSTEM_ON_ECHO_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FCW_WARNING_ECHO_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_FCW_SYSTEM_UNAVAILABLE_ECHO_MESSAGE,target_app),
#endif

#ifdef CONFIG_SAS
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_YELLOW_LAMP_FLASH_AT_HALFHZ,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_YELLOW_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_GREEN_LAMP_FLASH_AT_ONEHZ,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_GREEN_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_SPEED_LAMP,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_SPEED_LAMP_SPEED_VALUE_FLASH_AT_HALFHZ,target_app),										
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_FAULT_MESSAGE,target_app),
	__DECLARE_MSG_ENTRY( SERVICE_DI_SAS_SYSTEM_SPEED_LIMIT_REMINDER_MESSAGE,target_app),
#endif	

#endif

//{{{}
};


const int special_size = array_size(SpecialMsgTable);



