#ifndef _Message_Def_
#define _Message_Def_
typedef enum ModuleID_Tag
{
	MODULE_IPC_UART_DATA = 0x0001,
	MODULE_SERVICE_DI_DATA_ANALISIS = 0x0101,
	MODULE_SERVICE_SYSTEM,
	MODULE_SERVICE_POWER,
	MODULE_SERVICE_CAMERA,
	MODULE_SERVICE_LOG,
	MODULE_SERVICE_WINDOWS_MGR,
	MODULE_SERVICE_UPGRADE,
	MODULE_SERVICE_AUDIO_MGR,
	MODULE_APP_CLUSTER = 0x0201,
	MODULE_ID_MAX
}ModuleID_ENUM;

typedef enum SERVICE_DI_MessageID_Tag
{
	SERVICE_DI_SEAT_BELT_WARNING_SOUND	= (MODULE_SERVICE_DI_DATA_ANALISIS<<16)+0,	/*	0	*/
	SERVICE_DI_DIRECTION_INDICATOR_LEFT_HAND_LAMP_TICK_TOCK	,	/*	1	*/
	SERVICE_DI_DIRECTION_INDICATOR_RIGHT_HAND_LAMP_TICK_TOCK	,	/*	2	*/
	SERVICE_DI_PDC_STATUS_SOUND	,	/*	3	*/
	SERVICE_DI_FRONT_LEFT_OBSTACLE_RANGE	,	/*	4	*/
	SERVICE_DI_FRONT_RIGHT_OBSTACLE_RANGE	,	/*	5	*/
	SERVICE_DI_FRONT_MIDDLE_LEFT_OBSTACLE_RANGE	,	/*	6	*/
	SERVICE_DI_FRONT_MIDDLE_RIGHT_OBSTACLE_RANGE	,	/*	7	*/
	SERVICE_DI_REAR_LEFT_OBSTACLE_RANGE	,	/*	8	*/
	SERVICE_DI_REAR_RIGHT_OBSTACLE_RANGE	,	/*	9	*/
	SERVICE_DI_REAR_MIDDLE_LEFT_OBSTACLE_RANGE	,	/*	10	*/
	SERVICE_DI_REAR_MIDDLE_RIGHT_OBSTACLE_RANGE	,	/*	11	*/
	SERVICE_DI_FRONT_CLOSEST_OBSTACLE_DISTANCE	,	/*	12	*/
	SERVICE_DI_REAR_CLOSEST_OBSTACLE_DISTANCE	,	/*	13	*/
	SERVICE_DI_DOOR_LF	,	/*	14	*/
	SERVICE_DI_DOOR_LF_OPEN_RUN	,	/*	15	*/
	SERVICE_DI_DOOR_LF_OPEN_STOP	,	/*	16	*/
	SERVICE_DI_DOOR_LF_OPEN_POWEROFF	,	/*	17	*/
	SERVICE_DI_DOOR_RF	,	/*	18	*/
	SERVICE_DI_DOOR_RF_OPEN_RUN	,	/*	19	*/
	SERVICE_DI_DOOR_RF_OPEN_STOP	,	/*	20	*/
	SERVICE_DI_DOOR_RF_OPEN_POWEROFF	,	/*	21	*/
	SERVICE_DI_DOOR_LB	,	/*	22	*/
	SERVICE_DI_DOOR_LB_OPEN_RUN	,	/*	23	*/
	SERVICE_DI_DOOR_LB_OPEN_STOP	,	/*	24	*/
	SERVICE_DI_DOOR_LB_OPEN_POWEROFF	,	/*	25	*/
	SERVICE_DI_DOOR_RB	,	/*	26	*/
	SERVICE_DI_DOOR_RB_OPEN_RUN	,	/*	27	*/
	SERVICE_DI_DOOR_RB_OPEN_STOP	,	/*	28	*/
	SERVICE_DI_DOOR_RB_OPEN_POWEROFF	,	/*	29	*/
	SERVICE_DI_DOOR_EC	,	/*	30	*/
	SERVICE_DI_DOOR_EC_OPEN_RUN	,	/*	31	*/
	SERVICE_DI_DOOR_EC_OPEN_STOP	,	/*	32	*/
	SERVICE_DI_DOOR_EC_OPEN_POWEROFF	,	/*	33	*/
	SERVICE_DI_DOOR_T	,	/*	34	*/
	SERVICE_DI_DOOR_T_OPEN_RUN	,	/*	35	*/
	SERVICE_DI_DOOR_T_OPEN_STOP	,	/*	36	*/
	SERVICE_DI_DOOR_T_OPEN_POWEROFF	,	/*	37	*/
	SERVICE_DI_CRUISE_ECHO_MESSAGE	,	/*	38	*/
	SERVICE_DI_ENGINE_COOLANT_TEMP_ECHO_MESSAGE	,	/*	39	*/
	SERVICE_DI_DRIVE_BY_WIRE_LAMP_ECHO_MESSAGE	,	/*	40	*/
	SERVICE_DI_MIL_ECHO_MESSAGE	,	/*	41	*/
	SERVICE_DI_ALTERNATOR_CHARGE_ECHO_MESSAGE	,	/*	42	*/
	SERVICE_DI_SHED_LEVEL_ECHO_MESSAGE	,	/*	43	*/
	SERVICE_DI_OIL_PRESSURE_ECHO_MESSAGE	,	/*	44	*/
	SERVICE_DI_STOP_START_ACTIVE_ECHO_MESSAGE	,	/*	45	*/
	SERVICE_DI_STOP_START_FAULT_MESSAGE	,	/*	46	*/
	SERVICE_DI_EPS_FAULT_ECHO_MESSAGE	,	/*	47	*/
	SERVICE_DI_SAS_FAULT_ECHO_MESSAGE	,	/*	48	*/
	SERVICE_DI_SAS_UNCALIBRATION_ECHO_MESSAGE	,	/*	49	*/
	SERVICE_DI_TPMS_WARN_ECHO_MESSAGE	,	/*	50	*/
	SERVICE_DI_TPMS_SYSTEM_FAIL_ECHO_MESSAGE	,	/*	51	*/
	SERVICE_DI_ABS_ECHO_MESSAGE	,	/*	52	*/
	SERVICE_DI_HDC_FAULT_MESSAGE	,	/*	53	*/
	SERVICE_DI_DSC_FAULT_MESSAGE	,	/*	54	*/
	SERVICE_DI_TC_FAULT_MESSAGE	,	/*	55	*/
	SERVICE_DI_DSC_OFF_MESSAGE	,	/*	56	*/
	SERVICE_DI_TC_OFF_MESSAGE	,	/*	57	*/
	SERVICE_DI_BRAKE_SYSTEM_ECHO_MESSAGE	,	/*	58	*/
	SERVICE_DI_SEAT_BELT_DRIVER_ECHO_MESSAGE	,	/*	59	*/
	SERVICE_DI_SEAT_BELT_PASSENGER_ECHO_MESSAGE	,/*	60	*/
	SERVICE_DI_SRS_ECHO_MESSAGE	,	/*	61	*/
	SERVICE_DI_MAIN_BEAM_ECHO_MESSAGE	,	/*	62	*/
	SERVICE_DI_ENGINE_DISABLED_MESSAGE	,	/*	63	*/
	SERVICE_DI_KEY_BATTERY_LOW_MESSAGE	,	/*	64	*/
	SERVICE_DI_ALARM_TRIGGERED_MESSAGE	,	/*	65	*/
	SERVICE_DI_TCCM_STATUS_ECHO_MESSAGE	,	/*	66	*/
	SERVICE_DI_TCCM_FAULT_ECHO_MESSAGE	,	/*	67	*/
	SERVICE_DI_TCCM_OVERHEATED_ECHO_MESSAGE	,	/*	68	*/
	SERVICE_DI_AUTOHOLD_FAULT_ECHO_MESSAGE	,	/*	69	*/
	SERVICE_DI_EPB_FAULT_ECHO_MESSAGE	,	/*	70	*/
	SERVICE_DI_LOW_FUEL_ECHO_MESSAGE_LOW	,	/*	71	*/
	SERVICE_DI_FUEL_SIGNAL_ERROR_ECHO_MESSAGE	,	/*	72	*/
	SERVICE_DI_DIPPED_BEAM_LAMP_MESSAGE	,	/*	73	*/
	SERVICE_DI_SIDELIGHTS_ON_ECHO_MESSAGE	,	/*	74	*/
	SERVICE_DI_FRONT_FOG_ON_ECHO_MESSAGE	,	/*	75	*/
	SERVICE_DI_REAR_FOG_ON_ECHO_MESSAGE	,	/*	76	*/
	SERVICE_DI_AUTO_MAIN_BEAM_ECHO_MESSAGE	,	/*	77	*/
	SERVICE_DI_USE_KEY_TO_START_MESSAGE	,	/*	78	*/
	SERVICE_DI_PRESS_CLUTCH_MESSAGE	,	/*	79	*/
	SERVICE_DI_PRESS_BRAKE_MESSAGE	,	/*	80	*/
	SERVICE_DI_NO_KEY_DETECTED_PRESS_CLUTCH_MESSAGE	,	/*	81	*/
	SERVICE_DI_NO_KEY_DETECTED_PRESS_BRAKE_MESSAGE	,	/*	82	*/
	SERVICE_DI_CLUTCH_SWITCH_FAULT_MESSAGE	,	/*	83	*/
	SERVICE_DI_CLOSE_DRIVER_DOOR_TO_RESTART_MESSAGE	,	/*	84	*/
	SERVICE_DI_FASTEN_SEATBELT_TO_RESTART_MESSAGE	,	/*	85	*/
	SERVICE_DI_SELECT_NEUTRAL_TO_RESTART_MESSAGE	,	/*	86	*/
	SERVICE_DI_STOP_START_ON_MESSAGE	,	/*	87	*/
	SERVICE_DI_STOP_START_OFF_MESSAGE	,	/*	88	*/
	SERVICE_DI_AUTOHOLD_ASSIST1_MESSAGE	,	/*	89	*/
	SERVICE_DI_AUTOHOLD_ASSIST2_MESSAGE	,	/*	90	*/
	SERVICE_DI_AUTOHOLD_ASSIST3_MESSAGE	,	/*	91	*/
	SERVICE_DI_AUTOHOLD_ASSIST4_MESSAGE	,	/*	92	*/
	SERVICE_DI_AUTOHOLD_ASSIST5_MESSAGE	,	/*	93	*/
	SERVICE_DI_HHC_FAIL_MESSAGE	,	/*	94	*/
	SERVICE_DI_LOCK_STATUS_ON_MESSAGE	,	/*	95	*/
	SERVICE_DI_LOCK_STATUS_OFF_MESSAGE	,	/*	96	*/
	SERVICE_DI_LOCK_STATUS_FAIL_MESSAGE	,	/*	97	*/
	SERVICE_DI_IGNITION_KEY_ON_MESSAGE	,	/*	98	*/
	SERVICE_DI_PRESS_BUTTON_ENGINE_OFF_MESSAGE	,	/*	99	*/
	SERVICE_DI_LONG_PRESS_BUTTON_ENGINE_OFF_MESSAGE	,	/*	100	*/
	SERVICE_DI_DOUBLE_PRESS_BUTTON_ENGINE_OFF_MESSAGE	,	/*	101	*/
	SERVICE_DI_PRESS_BRAKE_SHIFT_MESSAGE	,	/*	102	*/
	SERVICE_DI_TAKE_SMART_KEY_MESSAGE	,	/*	103	*/
	SERVICE_DI_PUT_SHIFTER_TO_PARK_MESSAGE	,	/*	104	*/
	SERVICE_DI_NO_SMART_KEY_DETECTED_MESSAGE	,	/*	105	*/
	SERVICE_DI_PUT_KEY_INTO_BACKUP_POSITION_MESSAGE	,	/*	106	*/
	SERVICE_DI_IGNITION_RELAY_FAILED_MESSAGE	,	/*	107	*/
	SERVICE_DI_START_STOP_BUTTON_FAILED_MESSAGE	,	/*	108	*/
	SERVICE_DI_LEFT_BRAKE_LAMP_FAILED_MESSAGE	,	/*	109	*/
	SERVICE_DI_RIGHT_BRAKE_LAMP_FAILED_MESSAGE	,	/*	110	*/
	SERVICE_DI_LEFT_DI_LIGHT_FAILED_MESSAGE	,	/*	111	*/
	SERVICE_DI_RIGHT_DI_LIGHT_FAILED_MESSAGE	,	/*	112	*/
	SERVICE_DI_LEFT_DIPPED_BEAM_FAILED_MESSAGE	,	/*	113	*/
	SERVICE_DI_RIGHT_DIPPED_BEAM_FAILED_MESSAGE	,	/*	114	*/
	SERVICE_DI_FRONT_SIDE_LIGHT_FAILED_MESSAGE	,	/*	115	*/
	SERVICE_DI_REAR_SIDE_LIGHT_FAILED_MESSAGE	,	/*	116	*/
	SERVICE_DI_LEFT_SIDE_LIGHT_FAILED_MESSAGE	,	/*	117	*/
	SERVICE_DI_RIGHT_SIDE_LIGHT_FAILED_MESSAGE	,	/*	118	*/
	SERVICE_DI_REAR_FOG_LIGHT_FAILED_MESSAGE	,	/*	119	*/
	SERVICE_DI_REVERSE_LAMP_FAILED_MESSAGE	,	/*	120	*/
	SERVICE_DI_DAY_TIME_RUNNING_LAMP_FAILED_MESSAGE	,	/*	121	*/
	SERVICE_DI_LIGHTS_ON_KEY_OUT_WARNING_MESSAGE	,	/*	122	*/
	SERVICE_DI_LOW_WASHER_FLUID_MESSAGE	,	/*	123	*/
	SERVICE_DI_DRIVER_WINDOW_OPEN_ECHO_MESSAGE	,	/*	124	*/
	SERVICE_DI_FRONT_PASSENGER_WINDOW_OPEN_ECHO_MESSAGE	,	/*	125	*/
	SERVICE_DI_REAR_LEFT_WINDOW_OPEN_ECHO_MESSAGE	,	/*	126	*/
	SERVICE_DI_REAR_RIGHT_WINDOW_OPEN_ECHO_MESSAGE	,	/*	127	*/
	SERVICE_DI_SUNROOF_OPEN_ECHO_MESSAGE	,	/*	128	*/
	SERVICE_DI_EPB_ASSIST1_MESSAGE	,	/*	129	*/
	SERVICE_DI_EPB_ASSIST2_MESSAGE	,	/*	130	*/
	SERVICE_DI_EPB_ASSIST3_MESSAGE	,	/*	131	*/
	SERVICE_DI_EPB_ASSIST4_MESSAGE	,	/*	132	*/
	SERVICE_DI_EPB_ASSIST5_MESSAGE	,	/*	133	*/
	SERVICE_DI_AFS_FAULT_MESSAGE	,	/*	134	*/
	SERVICE_DI_BATTERY_FAIL_MESSAGE	,	/*	135	*/
	SERVICE_DI_GEARBOX_OVERHEAT_MESSAGE	,	/*	136	*/
	SERVICE_DI_OVERSPEED_WARNING_MESSAGE	,	/*	137	*/
	SERVICE_DI_FL_TYRE_LOW_MESSAGE	,	/*	138	*/
	SERVICE_DI_FR_TYRE_LOW_MESSAGE	,	/*	139	*/
	SERVICE_DI_RL_TYRE_LOW_MESSAGE	,	/*	140	*/
	SERVICE_DI_RR_TYRE_LOW_MESSAGE	,	/*	141	*/
	SERVICE_DI_ENGAGE_PARK_OR_NEUTRAL_TO_START_MESSAGE	,	/*	142	*/
	SERVICE_DI_INITIALIZE_DRIVER_WINDOW_MESSAGE	,	/*	143	*/
	SERVICE_DI_PEPS_ANTENNA_FAULT_MESSAGE	,	/*	144	*/
	SERVICE_DI_SEAT_POSITION_MEMORY_SET_SUCCESS_MESSAGE	,	/*	145	*/
	SERVICE_DI_POWER_LIFTGATE_SYSTEM_FAULT_MESSAGE	,	/*	146	*/
	SERVICE_DI_POWER_LIFTGATE_SYSTEM_LIMIT_MESSAGE	,	/*	147	*/
	SERVICE_DI_POWER_LIFTGATE_PUT_IN_PARK_REQUEST_MESSAGE	,	/*	148	*/
	SERVICE_DI_POWER_LIFTGATE_MANUAL_CLOSE_REQUEST_MESSAGE	,	/*	149	*/
	SERVICE_DI_SIA_REMINDER_SUGGEST_MESSAGE	,	/*	150	*/
	SERVICE_DI_FICM_SIA_REMINDER_SUGGEST_MESSAGE	,	/*	151	*/
	SERVICE_DI_FICM_SIA_REMINDER_IMMEDIATELY_MESSAGE	,	/*	152	*/
	SERVICE_DI_IPK_OVERHEATING_MESSGE	,	/*	153	*/
	SERVICE_DI_LEFT_REGULATE_STREERING_MESSAGE	,	/*	154	*/
	SERVICE_DI_RIGHT_REGULATE_STEERING_MESSAGE	,	/*	155	*/
	SERVICE_DI_KEY_OFF_WHEEL_NOT_STRAIGHT_REMINDER_MESSAGE	,	/*	156	*/
	SERVICE_DI_CRUISE_LAMP	,	/*	157	*/
	SERVICE_DI_ENGINE_COOLANT_TEMP_LAMP	,	/*	158	*/
	SERVICE_DI_DRIVE_BY_WIRE_LAMP	,	/*	159	*/
	SERVICE_DI_MIL_LAMP	,	/*	160	*/
	SERVICE_DI_ALTERNATOR_CHARGE_LAMP	,	/*	161	*/
	SERVICE_DI_OIL_PRESSURE_LAMP	,	/*	162	*/
	SERVICE_DI_STOP_START_ACTIVE_LAMP	,	/*	163	*/
	SERVICE_DI_STOP_START_FAULT_LAMP	,	/*	164	*/
	SERVICE_DI_STEERING_WHEEL_LAMP	,	/*	165	*/
	SERVICE_DI_TPMS_LAMP	,	/*	166	*/
	SERVICE_DI_ABS_LAMP	,	/*	167	*/
	SERVICE_DI_HDC_LAMP	,	/*	168	*/
	SERVICE_DI_DSC_LAMP	,	/*	169	*/
	SERVICE_DI_DSC_OFF_LAMP	,	/*	170	*/
	SERVICE_DI_BRAKE_SYSTEM_LAMP	,	/*	171	*/
	SERVICE_DI_SEAT_BELT_LAMP	,	/*	172	*/
	SERVICE_DI_SRS_LAMP	,	/*	173	*/
	SERVICE_DI_MAIN_BEAM_LAMP	,	/*	174	*/
	SERVICE_DI_DIRECTION_INDICATOR_LEFT_HAND_LAMP	,	/*	175	*/
	SERVICE_DI_DIRECTION_INDICATOR_RIGHT_HAND_LAMP	,	/*	176	*/
	SERVICE_DI_VEHICLE_WITH_KEY_LAMP	,	/*	177	*/
	SERVICE_DI_TCCM_LAMP	,	/*	178	*/
	SERVICE_DI_EPB_STATUS_LAMP	,	/*	179	*/
	SERVICE_DI_EPB_FAULT_LAMP	,	/*	180	*/
	SERVICE_DI_LOW_FUEL_LAMP	,	/*	181	*/
	SERVICE_DI_ECO_LAMP	,	/*	182	*/
	SERVICE_DI_DIPPED_BEAM_LAMP	,	/*	183	*/
	SERVICE_DI_LIGHT_ON_LAMP	,	/*	184	*/
	SERVICE_DI_FRONT_FOG_LAMP	,	/*	185	*/
	SERVICE_DI_REAR_FOG_LAMP	,	/*	186	*/
	SERVICE_DI_AUTO_MAIN_BEAM_LAMP	,	/*	187	*/
	SERVICE_DI_CONFIG_FUNCTION_ACTIVE_SAFETY	,	/*	188	*/
	SERVICE_DI_CONFIG_FUNCTION_MEDIA	,	/*	189	*/
	SERVICE_DI_CONFIG_FUNCTION_COMMUNICATION	,	/*	190	*/
	SERVICE_DI_CONFIG_FUNCTION_TAB_INDEX	,	/*	191	*/
	SERVICE_DI_NAVIGATION_ABNORMAL_DISPLAY	,	/*	192	*/
	SERVICE_DI_VIDEO_ABNORMAL_DISPLAY	,	/*	193	*/
	SERVICE_DI_TELEPHONE_ABNORMAL_DISPLAY	,	/*	194	*/
	SERVICE_DI_SPEED	,	/*	195	*/
	SERVICE_DI_CONFIG_FUNCTION_REVERSING_CAMERA	,	/*	196	*/
	SERVICE_DI_PDC_SYSTEM_FAILED_MESSAGE	,	/*	197	*/
	SERVICE_DI_RVC	,	/*	198	*/
	SERVICE_DI_AVERAGE_SPEED_A	,	/*	199	*/
	SERVICE_DI_AVERAGE_SPEED_C	,	/*	200	*/
	SERVICE_DI_TRIPMETER_A	,	/*	201	*/
	SERVICE_DI_TRIPMETER_C	,	/*	202	*/
	SERVICE_DI_DIS_TO_NEXT_MAINTENANCE	,	/*	203	*/
	SERVICE_DI_AVERAGE_FUEL_CONSUMPTION_A1	,	/*	204	*/
	SERVICE_DI_AVERAGE_FUEL_CONSUMPTION_A2	,	/*205	*/
	SERVICE_DI_AVERAGE_FUEL_CONSUMPTION_C1	,	/*	206	*/
	SERVICE_DI_AVERAGE_FUEL_CONSUMPTION_C2	,	/*	207	*/
	SERVICE_DI_INSTANTANEOUS_FUEL_CONSUMPTION1	,	/*	208	*/
	SERVICE_DI_INSTANTANEOUS_FUEL_CONSUMPTION2	,	/*	209	*/
	SERVICE_DI_AVERAGE_FUEL_CONSUMPTION_TREND_SAMPING	,	/*	210	*/
	SERVICE_DI_STEERING_WHEEL_ANGLE	,	/*	211	*/
	SERVICE_DI_BATTERY_STATUS_DISPLAY	,	/*	212	*/
	SERVICE_DI_BATTERY_STATUS_SOC_STATE	,	/*	213	*/
	SERVICE_DI_TYRE_PRESSURE	,	/*	214	*/
	SERVICE_DI_THROTTLE_POSITION	,	/*	215	*/
	SERVICE_DI_DRIVE_TIME_A	,	/*	216	*/
	SERVICE_DI_DRIVE_TIME_C	,	/*	217	*/
	SERVICE_DI_NEXT_MAINTENANCE_DATE	,	/*	218	*/
	SERVICE_DI_ENGINE_COOLANT_TEMP	,	/*	219	*/
	SERVICE_DI_VERSION_INFORMATION	,	/*	220	*/
	SERVICE_DI_VERSION_SOFTWARE_MAJOR	,	/*	221	*/
	SERVICE_DI_VERSION_SOFTWARE_MINOR	,	/*	222	*/
	SERVICE_DI_BUTTON_KEY_RIGHT	,	/*	223	*/
	SERVICE_DI_BUTTON_KEY_LEFT	,	/*	224	*/
	SERVICE_DI_BUTTON_KEY_UP	,	/*	225	*/
	SERVICE_DI_BUTTON_KEY_DOWN	,	/*	226	*/
	SERVICE_DI_BACKLIGHT	,	/*	227	*/
	SERVICE_DI_POWER_MODE	,	/*	228	*/
	SERVICE_DI_BUTTON_KEY_ENTER	,	/*	229	*/
	SERVICE_DI_BUTTON_KEY_6	,	/*	230	*/
	SERVICE_DI_LCD_TEMP	,	/*	231	*/
	SERVICE_DI_ANGULAR_CONFIGURATION_OF_ROTATIONAL_SPEED	,	/*	232	*/
	SERVICE_DI_FUEL_GAUGE	,	/*	233	*/
	SERVICE_DI_USER_TIME_STANDARD	,	/*	234	*/
	SERVICE_DI_USER_TIME_FORMAT	,	/*	235	*/
	SERVICE_DI_USER_LANGUAGE_SETTING	,	/*	236	*/
	SERVICE_DI_USER_ODO_UNIT	,	/*	237	*/
	SERVICE_DI_USER_TEMPERATURE_UNIT	,	/*	238	*/
	SERVICE_DI_USER_FUEL_CONSUMPTION_UNIT	,	/*	239	*/
	SERVICE_DI_WIC_RECORD	,	/*	240	*/
	SERVICE_DI_VEHICLE_HEALTH_STATUS	,	/*	241	*/
	SERVICE_DI_WORKMODE	,	/*	242	*/
	SERVICE_DI_DATE	,	/*	243	*/
	SERVICE_DI_GEAR	,	/*	244	*/
	SERVICE_DI_ODOMETER	,	/*	245	*/
	SERVICE_DI_INSTRUMENT_TOPIC	,	/*	246	*/
	SERVICE_DI_MILAGE	,	/*	247	*/
	SERVICE_DI_SPEED_LIMIT	,	/*	248	*/
	SERVICE_DI_OUTSIDE_AIR_TEMP, /*249*/
	SERVICE_DI_OVER_SPEED_WARNING_LAMP_HALFHZ	,	/*	250	*/
	SERVICE_DI_TACHOMETER	,	/*	251	*/
	SERVICE_DI_AT_OR_MT,	/*252*/

	SERVICE_DI_ATS_MODE_MESSAGE,
	SERVICE_DI_ALL_WHEEL_DRIVE_INSERVICE_DICATION_MESSAGE,
	SERVICE_DI_LEFT_REGULATE_STEERING_MESSAGE,
	SERVICE_DI_LOW_FUEL_ECHO_MESSAGE_CRITICAL,
	SERVICE_DI_ESCL_FAULT_LEVEL2_ECHO_MESSAGE,
	SERVICE_DI_LOAD_SHED_LEVEL2_ECHO_MESSAGE,
	SERVICE_DI_LOAD_SHED_LEVEL3_ECHO_MESSAGE,
	SERVICE_DI_ASL_OVERSPEED_MESSAGE,
	SERVICE_DI_SIA_REMINDER_MESSAGE,
	SERVICE_DI_FICM_SIA_REMINDER_IMMESERVICE_DIATELY_MESSAGE,
	SERVICE_DI_EPB_AUDIO,
	
	
	/*adas added by yindongping*/

	/*84*/
	SERVICE_DI_ACC_SYSTEM_FAULT_LAMP,
	SETVICE_DI_ACC_SYSTEM_ACTIVE_GREEN_LAMP,
	SERVICE_DI_ACC_SYSTEM_STAND_BY_YELLOW_LAMP,
	
	/*85*/
	SERVICE_DI_ACC_SYSTEM_STAND_BY_MESSAGE,
	SERVICE_DI_ACC_TAKE_OVER_MESSAGE, 
	SERVICE_DI_ACC_SENSOR_BLOCK_MESSAGE,/*with sound*/
	SERVICE_DI_ACC_SYSTEM_CANCEL_REQUEST_MESSAGE,
	SERVICE_DI_ACC_SYSTEM_UNAVAILABLE_MESSAGE,/*with gong1*/
	
	/*86*/
	SERVICE_DI_ACC_SYSTEM_OFF_MESSAGE,
	SERVICE_DI_ACC_SYSTEM_ON_MESSAGE,
	SERVICE_DI_ACC_DRIVER_SELECT_TARGET_SPEED_ENABLE,
	SERVICE_DI_ACC_CAR_TYPE0,
	SERVICE_DI_ACC_CAR_TYPE1,
	SERVICE_DI_ACC_CAR_TYPE2,
	SERVICE_DI_FRONT_CAR_DISAPPEARED,
	
	/*87*/
	SERVICE_DI_FRONT_CAR_ON_POSITION,
	SERVICE_DI_TIME_DISTANCE_DISAPPEARED,
	
	/*88*/
	SERVICE_DI_TIME_DISTANCE_POSITION_COLOR,
	
	/*89*/

	SERVICE_DI_FVCM_FAULT_MESSASGE,/*with gong1*/
	SERVICE_DI_ADAS_TAB_JUMP_REQUEST,
	
	/*90*/
	SERVICE_DI_ACC_DRIVER_SELECT_TARGET_SPEED,
	
	/*91*/
	SERVICE_DI_ACC_FUNCTION_NOT_AVAIBLE,
	SERVICE_DI_DRIVER_SELECT_TARGET_DISTANCE_LEVEL,
	
	/*92*/
	/*93*/
	/*94*/
	/*95*/
	SERVICE_DI_AEB_SYSTEM_OFF_LAMP,
	SERVICE_DI_AEB_SYSTEM_FAULT_FLASH,	

	/*96*/
	SERVICE_DI_AEB_SYSTEM_UNAVAILABE_MESSAGE,/*with gong1*/
	SERVICE_DI_AEB_SYSTEM_OFF_MESSAGE,
	SERVICE_DI_AEB_SYSTEM_ON_MESSAGE,
	SERVICE_DI_AEB_ACTIVE_MESSAGE,

	/*97*/
	SERVICE_DI_LDW_ACTIVE_LAMP_GREEN,
	SERVICE_DI_LDW_FAULT_LAMP_YELLOW, 
	SERVICE_DI_LDW_OFF_LAMP_YELLOW,
	
	/*98*/
	SERVICE_DI_LDW_SYSTEM_OFF_ECHO_MESSAGE,/*with gong1*/
	SERVICE_DI_LDW_STAND_BY_ECHO_MESSAGE,
	
	SERVICE_DI_LDW_CAR_TYPE0,
	SERVICE_DI_LDW_CAR_TYPE1,
	SERVICE_DI_LDW_CAR_TYPE2,
	SERVICE_DI_LDW_LANES_DISPLAY,
	SERVICE_DI_LDW_AUDIBLE_WARNING_SPECIAL_GONG,
	
	/*99*/
	SERVICE_DI_LDW_SYSTEM_CROSSING_LANE_MESSAGE,
	SERVICE_DI_LDW_UNAVAILABLE_MESSAGE,
	SERVICE_DI_LDW_LEFT_LANE_STATUS,
	SERVICE_DI_LDW_RIGHT_LANE_STATUS,
	
	/*100*/
	SERVICE_DI_FCW_SYSTEM_OFF_LAMP,
	SERVICE_DI_FCW_SYSTEM_FAULT_LAMP_FLASH,
	SERVICE_DI_FCW_SYSTEM_OFF_ECHO_MESSAGE,
	SERVICE_DI_FCW_SYSTEM_ON_ECHO_MESSAGE,
	
	/*101*/
	SERVICE_DI_FCW_WARNING_ECHO_MESSAGE,/*with gong1*/
	SERVICE_DI_FCW_SYSTEM_UNAVAILABLE_ECHO_MESSAGE,/*with sound*/
													/*0--no sound*/
													/*1--gong1*/
													/*2--repeat gong*/
	/*102*/											
	SERVICE_DI_SAS_SYSTEM_YELLOW_LAMP_FLASH_AT_HALFHZ,
	SERVICE_DI_SAS_SYSTEM_YELLOW_LAMP,
	SERVICE_DI_SAS_SYSTEM_GREEN_LAMP_FLASH_AT_ONEHZ,
	SERVICE_DI_SAS_SYSTEM_GREEN_LAMP,
	SERVICE_DI_SAS_SYSTEM_SPEED_LAMP,
	SERVICE_DI_SAS_SYSTEM_SPEED_LAMP_SPEED_VALUE_FLASH_AT_HALFHZ,										
		
	/*103*/
	SERVICE_DI_SAS_SYSTEM_FAULT_MESSAGE/*with gong1*/,
	SERVICE_DI_SAS_SYSTEM_SPEED_LIMIT_REMINDER_MESSAGE,
		
												

	SERVICE_DI_MESSAGE_MAX	

}SERVICE_DI_MessageID_ENUM;

typedef enum APPCLUSTER_MessageID_Tag
{
	APP_CLUSTER_TRIPMETERA_CLEAR	= (MODULE_APP_CLUSTER<<16)+0,
	APP_CLUSTER_AVERAGE_SPEEDA_CLEAR	,
	APP_CLUSTER_AVERAGE_FUELA_CLEAR	,
	APP_CLUSTER_BACKLIGHT_SET	,
	APP_CLUSTER_TRIPMETERC_CLEAR	,
	APP_CLUSTER_AVERAGE_SPEEDC_CLEAR	,
	APP_CLUSTER_AVERAGE_FUELC_CLEAR	,

	
	APP_CLUSTER_TIME_SET	,
	
	
	APP_CLUSTER_TRAVEL_TIMEA_CLEAR	,
	APP_CLUSTER_TRAVEL_TIMEC_CLEAR	,
	APP_CLUSTER_TOPIC_SET	,
	APP_CLUSTER_TIMESTD_SET	,
	APP_CLUSTER_TIMEFORMAT_SET	,
	APP_CLUSTER_SPEEDLIMIT_SET	,
	APP_CLUSTER_LANGUAGE_SET	,
	APP_CLUSTER_ODOUNIT_SET	,
	APP_CLUSTER_TEMPUNIT_SET	,
	APP_CLUSTER_FUELUNIT_SET	,
	APP_CLUSTER_TABINDEX_CHG	,
	APP_CLUSTER_NEXT_MAINTEN_DIST	,
	APP_CLUSTER_NEXT_MAINTEN_DATE	,
	APP_CLUSTER_POPUP_CHIME	,
	APP_CLUSTER_STATUS ,
	
	APP_CLUSTER_SELFCHECK_READY,
	APP_CLUSTER_LCD_POWER,
	
	APP_CLUSTER_MESSAGE_MAX
}APPCLUSTER_MessageID_ENUM;

typedef enum IPC_UART_MessageID_Tag
{
	IPC_UART_DATA_GENERAL_UP = (MODULE_IPC_UART_DATA<<16)+0,
	IPC_UART_DATA_SPECIAL_UP,
	
	IPC_UART_MESSAGE_MAX
}IPC_UART_MessageID_ENUM;


typedef enum SERVICE_CAMERA_MessageID_Tag
{
	SERVICE_CAMERA_OFF = (MODULE_SERVICE_CAMERA<<16)+0,
	SERVICE_CAMERA_ON,
	
	SERVICE_CAMERA_MESSAGE_MAX
}SERVICE_CAMERA_MessageID_ENUM;

typedef enum SERVICE_SYSTEM_MessageID_Tag
{
	SERVICE_SYSTEM_READY = (MODULE_SERVICE_SYSTEM<<16)+0,
	
	SERVICE_SYSTEM_MESSAGE_MAX
}SERVICE_SYSTEM_MessageID_ENUM;

typedef enum SERVICE_POWER_MessageID_Tag
{
	SERVICE_POWER_OFF = (MODULE_SERVICE_POWER<<16)+0,
	SERVICE_POWER_ON,
	SERVICE_POWER_GPU_OVERHEAT,
	
	SERVICE_POWER_MESSAGE_MAX
}SERVICE_POWER_MessageID_ENUM;


typedef enum SERVICE_WINDOWS_MGR_MessageID_Tag
{
	SERVICE_WINDOWS_MGR_MESSAGE_START = (MODULE_SERVICE_WINDOWS_MGR<<16)+0,
	
	SERVICE_WINDOWS_MGR_MESSAGE_MAX
}SERVICE_WINDOWS_MGR_MessageID_ENUM;


typedef enum SERVICE_UPGRADE_MessageID_Tag
{
	SERVICE_UPGRADE_MESSAGE_START = (MODULE_SERVICE_UPGRADE<<16)+0,
	
	SERVICE_UPGRADE_MESSAGE_MAX
}SERVICE_UPGRADE_MessageID_ENUM;


typedef enum SERVICE_AUDIO_MGR_MessageID_Tag
{
	SERVICE_AUDIOMGR_CHIME = (MODULE_SERVICE_AUDIO_MGR<<16)+0,
	SERVICE_AUDIOMGR_TIMER,
	
	SERVICE_AUDIO_MGR_MESSAGE_MAX
}SERVICE_AUDIO_MGR_MessageID_ENUM;


typedef enum SERVICE_LOG_MessageID_Tag
{
	SERVICE_LOG_MESSAGE_START = (MODULE_SERVICE_LOG<<16)+0,
	
	SERVICE_LOG_MESSAGE_MAX
}SERVICE_LOG_MessageID_ENUM;


#endif

